import assert from 'node:assert/strict';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {readFileSync} from 'node:fs';
import Shell from '../app/shell';
import DailyWorkspace,{JobDetail} from '../app/daily';
import {collectJobs,nextStep,matchesAppliedPeriod,appliedDate,applicationRecorded,requestScoutAction,canSaveDiscovery} from '../app/daily-model';
import {makeDemo,agents,mapSheetData} from '../app/data';
import MatchOverview from '../app/qualifications';
import type {ScoutState} from '../app/scout';
import type {ReviewWorkflow} from '../app/workflow';

const at='2026-10-03T12:00:00Z',demo=makeDemo();
const state:ScoutState={protected:true,configured:true,enabled:true,status:'waiting',activeAgent:null,task:null,taskAt:null,lastRun:at,lastSuccess:at,nextCheck:at,error:null,stale:false,location:'Amsterdam',distance:25,terms:[],appId:'',profile:null,events:[],results:[],workflows:[],bridgeConfigured:true};
const fit={version:'synthetic',eligible:true,label:'Closer CV match',priority:2,roleMatches:['CRO'],coreSkills:['GA4'],sharedSkills:['GA4'],reasons:['CRO title and GA4 evidence align.'],blockers:[],limitations:[]};
const discovery={id:'SYNTHETIC-1',sourceId:'source-1',source:'Owner import',title:'Synthetic CRO analyst',employer:'Synthetic employer',location:'Amsterdam',salary:'Unknown',url:'https://example.test/cro',description:'Synthetic GA4 requirements',readAt:at,availability:'Owner-provided; unverified'};
const review:ReviewWorkflow={id:'HQ-W-synthetic',createdAt:at,cvReadAt:at,stage:'Coordinator review',managerDecision:'Needs owner review',job:discovery,receipts:[{id:'HQ-R-02',agentId:'02',at,inputReceipt:'HQ-R-01',title:'Compare CV evidence',method:'Local rules',findings:[{label:'Skill evidence',value:'GA4 appears in both sources'}],decision:'Screening candidate'}],draft:{kind:'Factual template',letter:'Synthetic letter',cvBullets:['Synthetic CV evidence'],interviewQuestions:['Synthetic question']},tracker:null,currentFit:fit,currentRules:true,superseded:false};
const native={...demo.jobs[0],id:'JOB-088',role:discovery.title,url:discovery.url,status:'Researching',applied:'',confirmation:''};
const data={...demo,mode:'synced' as const,stale:false,error:null,jobs:[native],events:[]};
const linked={...review,tracker:{recordId:native.id,eventId:'EVT-0177',at,duplicate:false}};
assert.equal(collectJobs(data,{...state,workflows:[linked]}).length,1,'Confirmed discovery and native job are one view');
assert.equal(collectJobs(data,{...state,workflows:[linked]})[0].job?.id,'JOB-088','Native IDs are preserved');
const newer={...review,id:'HQ-W-newer',createdAt:'2026-10-03T13:00:00Z'};
assert.equal(collectJobs(data,{...state,workflows:[linked,newer]})[0].review?.id,linked.id,'Confirmed native ID association has priority');
const older={...review,id:'HQ-W-older',createdAt:'2026-10-02T12:00:00Z'};
assert.equal(collectJobs({...data,jobs:[]},{...state,workflows:[older,review]}).length,1,'Latest evidence version is the normal view');
assert.equal(collectJobs(demo,{...state,workflows:[review]}).length,1,'Real private reviews do not mix with demo tracker jobs');
assert.equal(collectJobs(demo,{...state,protected:false,workflows:[review]}).some(i=>i.review),false,'Unprotected preview excludes private drafts');
const held={...review,id:'HQ-W-held',job:{...discovery,id:'SYNTHETIC-LEGAL',title:'Synthetic legal specialist'},currentFit:{...fit,eligible:false,label:'Requirement mismatch',blockers:['Legal background not documented']},draft:null};
assert.equal(collectJobs({...data,jobs:[]},{...state,workflows:[held]})[0].group,'Held');
assert(!canSaveDiscovery(held));assert(!canSaveDiscovery({...review,currentRules:false}));assert(!canSaveDiscovery({...review,draft:null}));assert(!canSaveDiscovery({...review,job:{...discovery,stale:true}}));assert(!canSaveDiscovery(linked));
assert(nextStep({key:'tracker:'+native.id,title:native.role,employer:native.employer,location:native.location,salary:native.salary,job:{...native,status:'Closed'},label:'Closed',group:'Tracked'}).title.includes('outcome'));
const props={mode:'jobs' as const,data:{...data,jobs:[]},state:{...state,workflows:[review,held]},refresh:async()=>{},sync:async()=>data,selected:'review:'+review.id,group:'Recommended' as const,onSelect:()=>{},onGroup:()=>{},onSettings:()=>{},onOffice:()=>{},onRecheck:()=>{},reviewBusy:false,reviewNotice:'',reviewError:'',replay:false};
const markup=renderToStaticMarkup(<DailyWorkspace {...props}/>);
assert(markup.includes('Synthetic CRO analyst'));assert(!markup.includes(held.job.title));assert(markup.includes('I reviewed the source'));assert(/disabled=""[^>]*><[^>]+>/.test(markup));assert(markup.includes('Add to tracker'));assert(!markup.includes('Private bridge secret'));assert(!markup.includes('Deployed Apps Script URL'));
const heldMarkup=renderToStaticMarkup(<JobDetail {...props} item={collectJobs({...data,jobs:[]},{...state,workflows:[held]})[0]} onBack={()=>{}}/>);assert(heldMarkup.includes('Legal background not documented'));assert(!heldMarkup.includes('Add to tracker'));
const staleMarkup=renderToStaticMarkup(<DailyWorkspace {...props} data={{...props.data,stale:true}}/>);assert(staleMarkup.includes('Refresh the tracker before saving'));
const application=collectJobs({...data,jobs:[{...native,status:'Applied',applied:'2026-10-02'}]},state)[0];const appliedMarkup=renderToStaticMarkup(<JobDetail {...props} item={application} onBack={()=>{}}/>);assert(appliedMarkup.includes('Outlook evidence'));assert(!appliedMarkup.includes('Mark as applied'));
const detailMarkup=renderToStaticMarkup(<JobDetail {...props} item={collectJobs(data,state)[0]} onBack={()=>{}}/>);assert(detailMarkup.includes('I&#x27;ve applied'));assert(detailMarkup.includes('Your decision beside agent advice'));assert(detailMarkup.includes('Open vacancy to apply'));assert(!detailMarkup.includes('Outlook evidence'));
const setup=renderToStaticMarkup(<DailyWorkspace {...props} mode="today"/>);assert(setup.includes('Find jobs'));assert(!setup.includes('HQ_BRIDGE_SECRET'));
(globalThis as any).window={location:{hash:''},history:{pushState(){}}};const root=renderToStaticMarkup(<Shell/>);const nav=root.match(/<nav class="sidebar"[\s\S]*?<\/nav>/)?.[0]||'';assert.equal((nav.match(/aria-label="(?:Today|Jobs|My CV|Settings)"/g)||[]).length,4,'four destinations, no 3D office');assert(root.includes('Your job hunt, today.'),'Today is the landing page');assert(root.includes('Demo · fictional records'),'without a database the page says it is a demo');assert(!/canvas|three|studio/i.test(nav));assert(!root.includes('vacancy-dialog'));
const css=readFileSync('app/daily.css','utf8');assert(css.includes('@media(max-width:760px)'));assert(css.includes('.daily-job-layout.has-selection .daily-job-list{display:none}'));assert(css.includes('prefers-reduced-motion'));assert(css.includes('focus-visible'));
let sends=0;await requestScoutAction('append',{workflowId:review.id,confirmReviewed:true},async(url,init)=>{sends++;assert.equal(url,'/api/scout');assert.deepEqual(JSON.parse(init!.body as string),{action:'append',workflowId:review.id,confirmReviewed:true});return Response.json({saved:true,message:'Synthetic Google receipt'});});assert.equal(sends,1);
await assert.rejects(()=>requestScoutAction('append',{},async()=>Response.json({message:'No receipt'})),/No new confirmation/);
await assert.rejects(()=>requestScoutAction('run',{},async()=>Response.json({error:'Wait for current task'},{status:400})),/Wait for current task/);
console.log('Daily workflow checks passed: unified native/draft identity, no demo mixing, held and stale guards, owner confirmation, same-page application/evidence, four main destinations and mobile/reduced-motion structure. Synthetic data only.');

const qualificationMarkup=renderToStaticMarkup(<MatchOverview description="SQL and GA4. Fluent Dutch required. Five years?" profile={{evidence:['SQL reporting was part of my work.'],readAt:at,sourceUrl:'https://example.test/cv'}} source="Synthetic vacancy" stale/>);assert(qualificationMarkup.includes('Qualifications: 1 of 3 documented'));assert(qualificationMarkup.includes('CV mention'));assert(qualificationMarkup.includes('Needs checking'));assert(qualificationMarkup.includes('Vacancy excerpt'));assert(qualificationMarkup.includes('stale source'));assert(!qualificationMarkup.includes('100%'));
const demoQualification=renderToStaticMarkup(<MatchOverview description="SQL" profile={{evidence:['SQL reporting was part of my work.']}} source="Demo" demo/>);assert(demoQualification.includes('Your private CV is not used'));assert(!demoQualification.includes('CV mention'));
const emptyQualification=renderToStaticMarkup(<MatchOverview description="Not separately documented" profile={null} source="Native Google notes"/>);assert(emptyQualification.includes('will not invent a match count'));
assert.deepEqual(agents.map(a=>a.name),['Tracker','Scout','Analyst']);
const aliasRecords=mapSheetData([{values:[['Record ID','Employer','Role title','Status']]},{values:[['Event ID','Record ID','Event date','Event type','Contact / actor'],['EVT-synthetic','','2026-10-03','Discovery','01 — Job Scout'],['EVT-next','','2026-10-03','Review','Analyst']]},{values:[]},{values:[]}]);assert.equal(aliasRecords.events[0].agentId,'01');assert.equal(aliasRecords.events[0].actor,'01 — Job Scout');assert.equal(aliasRecords.events[1].agentId,'02');
console.log('Office home and match overview checks passed: four destinations, name-only roles with historical ID attribution, day/night preference, mobile scene controls, evidence disclosures, partial counts and private-CV/demo separation.');

const appliedView=renderToStaticMarkup(<DailyWorkspace {...props} data={{...data,jobs:[{...native,applied:'2026-10-02',status:'Applied'}]}} state={state} selected="" group="Applied"/>);assert(appliedView.includes('Filter jobs by date'));assert(appliedView.includes('Applied on'));assert(appliedView.includes('All employers'));assert(appliedView.includes('All statuses'));assert(appliedView.includes('Past 7 days'));assert(appliedView.includes('Applied 2026-10-02'));
const dateNow=new Date('2026-10-03T13:00:00Z');assert(matchesAppliedPeriod('2026-09-27','Past 7 days',dateNow));assert(!matchesAppliedPeriod('2026-09-26','Past 7 days',dateNow));assert(!matchesAppliedPeriod('2026-10-04','Past 7 days',dateNow));assert(matchesAppliedPeriod('','All dates',dateNow));assert(matchesAppliedPeriod('','Date missing',dateNow));assert(!matchesAppliedPeriod('','Past 30 days',dateNow));assert.equal(appliedDate('2026-02-31'),'');assert.equal(appliedDate('2026-10-02T12:00:00Z'),'2026-10-02');assert(applicationRecorded({...native,status:'Rejected',applied:'2026-10-02'}));assert(!applicationRecorded({...native,status:'Rejected',applied:''}));
console.log('Applied view checks passed: direct office shortcut, visible employer/status/date filters, calendar windows, missing dates and later outcomes retained without inventing an application.');
