import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {makeDemo} from '../app/data';
import {collectJobs,nextStep} from '../app/daily-model';
import {feedbackIdentity,ownerFeedbackFor} from '../app/owner-feedback-model';
import {recordDiscoveryApplication,requestOwnerFeedback} from '../app/job-decisions-model';
import JobDecisions from '../app/job-decisions';
import DailyReportImport from '../app/daily-report-import';
import type {ScoutState} from '../app/scout';
import type {ReviewWorkflow} from '../app/workflow';
const at='2026-10-04T12:00:00Z',demo=makeDemo();
const state:ScoutState={protected:true,configured:true,enabled:false,status:'idle',activeAgent:null,task:null,taskAt:null,lastRun:at,lastSuccess:at,nextCheck:null,error:null,stale:false,location:'Amsterdam',distance:25,terms:[],appId:'',profile:null,events:[],results:[],workflows:[],bridgeConfigured:true};
const fit={version:'synthetic',eligible:true,label:'Closer CV match',priority:2,roleMatches:['analytics'],coreSkills:['GA4'],sharedSkills:['GA4'],reasons:[],blockers:[],limitations:[]};
const job={id:'DISCOVERY-1',sourceId:'one',source:'Owner import',title:'Digital analyst',employer:'Synthetic employer',location:'Amsterdam',salary:'Unknown',url:'https://careers.example.test/jobs/one',description:'GA4 and SQL requirements from an owner-provided excerpt.',readAt:at,availability:'Owner provided; unverified'};
const review:ReviewWorkflow={id:'HQ-W-synthetic',job,createdAt:at,cvReadAt:at,receipts:[],draft:{letter:'Synthetic draft',cvBullets:[],interviewQuestions:[],kind:'Local template'},stage:'Coordinator review',managerDecision:'Needs source / evidence review',tracker:null,currentRules:true,currentFit:fit,superseded:false};
const native={...demo.jobs[0],id:'JOB-101',employer:job.employer,role:job.title,url:job.url,status:'Researching',applied:'',confirmation:''};
const data={...demo,mode:'synced' as const,jobs:[native],events:[],stale:false,error:null};
const feedback={id:'HQ-F-synthetic',key:feedbackIdentity(job.url),jobId:job.id,recordId:null,decision:'not-fit' as const,reason:'Location / commute',at,source:'Owner preference · private HQ',history:[]};
const feedbackState={...state,workflows:[review],ownerFeedback:{[feedback.key]:feedback}};
let items=collectJobs({...data,jobs:[]},feedbackState);assert.equal(items[0].group,'Not a fit');assert.equal(items[0].review?.currentFit?.eligible,true);assert(nextStep(items[0]).title.includes('You marked'));
assert.equal(ownerFeedbackFor(feedbackState,job.url+'?utm_source=report',job.id)?.id,feedback.id);assert.equal(ownerFeedbackFor({...feedbackState,protected:false},job.url,job.id),undefined);
items=collectJobs({...data,jobs:[{...native,applied:'2026-10-03',status:'Interview'}]},feedbackState);assert.equal(items[0].group,'Applied','Owner screening never hides an existing application');assert(items[0].ownerFeedback);assert(nextStep(items[0]).title.includes('evidence'));
const actions=renderToStaticMarkup(<JobDecisions item={collectJobs({...data,jobs:[]},{...state,workflows:[review]})[0]} data={data} state={state} replay={false} refresh={async()=>{}} sync={async()=>data}/>);assert(actions.includes('I&#x27;ve applied'));assert(actions.includes('Not a fit'));assert(actions.includes('Separate from agent advice'));
const undo=renderToStaticMarkup(<JobDecisions item={collectJobs({...data,jobs:[]},feedbackState)[0]} data={data} state={feedbackState} replay={false} refresh={async()=>{}} sync={async()=>data}/>);assert(undo.includes('Return to review'));assert(undo.includes('The application status in your tracker is preserved'));
const held={...review,currentFit:{...fit,eligible:false},draft:null};const locked=renderToStaticMarkup(<JobDecisions item={collectJobs({...data,jobs:[]},{...state,workflows:[held]})[0]} data={data} state={state} replay refresh={async()=>{}} sync={async()=>data}/>);assert.equal((locked.match(/disabled=""/g)||[]).length,2);
const reportMarkup=renderToStaticMarkup(<DailyReportImport data={data} state={state} replay={false} refresh={async()=>{}} sync={async()=>data} onOpen={()=>{}}/>);assert(reportMarkup.includes('Import vacancies'));assert(reportMarkup.includes('Check jobs against my board'));assert(reportMarkup.includes('Email notes'));assert(!reportMarkup.includes('Client secret'));
const css=readFileSync('app/daily-report-import.css','utf8');assert(css.includes('@media(max-width:760px)'));assert(css.includes('min-height:44px'));assert(css.includes('focus-visible'));
const calls:string[]=[],bodies:object[]=[];let failOnce=true;
const fetcher:typeof fetch=async(url,init)=>{calls.push(String(url));if(url==='/api/scout'){assert.equal(JSON.parse(String(init!.body)).workflowId,review.id);return Response.json({saved:true,receipt:{recordId:native.id}});}if(url==='/api/snapshot')return Response.json(data);assert.equal(url,'/api/applications');bodies.push(JSON.parse(String(init!.body)));if(failOnce){failOnce=false;throw new Error('Response lost');}return Response.json({saved:true,receipt:{recordId:native.id,eventId:'EVT-203',status:'Applied',appliedOn:'2026-10-04',at,duplicate:true,source:'database connection'}});};
const attempt={requestId:'HQ-A-synthetic',appliedOn:'2026-10-04'};await assert.rejects(()=>recordDiscoveryApplication(review,attempt,fetcher),/Response lost/);assert.deepEqual(calls,['/api/scout','/api/snapshot','/api/applications']);
const result=await recordDiscoveryApplication(review,attempt,fetcher);assert.equal(result.recordId,native.id);assert.deepEqual(bodies[0],bodies[1],'Uncertain Applied retry uses the same request and optimistic expectations');assert.equal(calls.filter(u=>u==='/api/snapshot').length,1);
let writes=0;const reader=(snapshot:object):typeof fetch=>async url=>{if(url==='/api/scout')return Response.json({saved:true,receipt:{recordId:native.id}});if(url==='/api/snapshot')return Response.json(snapshot);writes++;throw new Error('Unexpected write');};
await assert.rejects(()=>recordDiscoveryApplication(review,{requestId:'x',appliedOn:'2026-10-04'},reader({...data,stale:true})),/fresh tracker record/);assert.equal(writes,0);
await assert.rejects(()=>recordDiscoveryApplication(review,{requestId:'x',appliedOn:'2026-10-04'},reader({...data,jobs:[{...native,status:'Closed'}]})),/outcome was preserved/);assert.equal(writes,0);
const prior=await recordDiscoveryApplication(review,{requestId:'x',appliedOn:'2026-10-04'},reader({...data,jobs:[{...native,status:'Interview',applied:'2026-10-03'}]}));assert(prior.alreadyRecorded);assert.equal(writes,0);
await assert.rejects(()=>recordDiscoveryApplication(held,{requestId:'x',appliedOn:'2026-10-04'},fetcher),/eligible, current review/);
await assert.rejects(()=>requestOwnerFeedback({},async()=>Response.json({saved:true})),/No saved owner preference/);
console.log('Owner decision / report UI checks passed: private preferences and undo, Applied history retained, verified native IDs, uncertain retry, stale/held/outcome guards, import disclosure and mobile accessibility.');
