import assert from 'node:assert/strict';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {readFileSync} from 'node:fs';
import {mapSheetData,makeDemo} from '../app/data';
import {calendarDate,sheetCalendarDate,matchesJobDate,jobDateInfo,earliestDiscovery,dateLabel} from '../app/job-dates';
import {collectJobs} from '../app/daily-model';
import JobDateFilters from '../app/job-date-filters';
import DailyWorkspace,{JobSummary,JobDetail} from '../app/daily';
import type {ScoutState} from '../app/scout';
import type {ReviewWorkflow} from '../app/workflow';
const now=new Date('2026-10-03T23:30:00Z'); // 4 October in Amsterdam.
assert(matchesJobDate('2026-10-04','Today','','',now));assert(!matchesJobDate('2026-10-03','Today','','',now));assert(!matchesJobDate('2026-10-05','Today','','',now));
assert(matchesJobDate('2026-09-28','Past 7 days','','',now));assert(!matchesJobDate('2026-09-27','Past 7 days','','',now));
assert(matchesJobDate('2026-09-05','Past 30 days','','',now));assert(!matchesJobDate('2026-09-04','Past 30 days','','',now));
for(const date of ['2026-09-01','2026-09-30'])assert(matchesJobDate(date,'Custom range','2026-09-01','2026-09-30',now));
assert(!matchesJobDate('2026-10-01','Custom range','2026-09-01','2026-09-30',now));assert(matchesJobDate('2026-09-01','Custom range','','2026-09-30',now));assert(matchesJobDate('2026-10-01','Custom range','2026-09-01','',now));assert(!matchesJobDate('2026-09-15','Custom range','2026-09-30','2026-09-01',now));
assert(matchesJobDate('','Date missing'));assert(matchesJobDate('bad date','Date missing'));assert(matchesJobDate('','All dates'));assert(!matchesJobDate('','Custom range'));assert.equal(calendarDate('2026-02-31'),'');assert.equal(calendarDate('10/4/2026'),'');assert.equal(calendarDate('2026-10-03T23:30:00Z'),'2026-10-04');
assert.equal(sheetCalendarDate('10/4/2026','en_US','Europe/Amsterdam'),'2026-10-04');assert.equal(sheetCalendarDate('10/4/2026','en_GB','Europe/Amsterdam'),'');assert.equal(sheetCalendarDate('2026-10-04','en_GB','Europe/Amsterdam'),'2026-10-04');
const ranges=[{values:[['Record ID','Employer','Role title','Status','Date found','Applied on'],['JOB-101','Synthetic employer','Digital analyst','Applied','9/30/2026','10/2/2026']]},{values:[['Event ID','Record ID','Event date','Event type']]},{values:[]},{values:[]}];
const mapped=mapSheetData(ranges,{locale:'en_US',timeZone:'Europe/Amsterdam'}),native=mapped.jobs[0];assert.equal(native.found,'9/30/2026');assert.equal(native.applied,'10/2/2026');assert.equal(native.foundDate,'2026-09-30');assert.equal(native.appliedDate,'2026-10-02');
const state:ScoutState={protected:true,configured:true,enabled:false,status:'idle',activeAgent:null,task:null,taskAt:null,lastRun:null,lastSuccess:null,nextCheck:null,error:null,stale:false,profile:null,results:[],events:[],location:'Amsterdam',distance:25,terms:[],appId:'',bridgeConfigured:true},data={...makeDemo(),...mapped,mode:'synced' as const,stale:false,error:null};
let item=collectJobs(data,state)[0];assert.equal(jobDateInfo(item,'found').date,'2026-09-30');assert.equal(jobDateInfo(item,'applied').date,'2026-10-02');assert.equal(jobDateInfo(item,'found').source,'Tracker · Date found');assert.equal(dateLabel({...item,job:{...native,foundDate:'',found:'unrecognised'}},'found'),'Date needs checking');
const fit={version:'synthetic',eligible:true,label:'Closer CV match',priority:2,roleMatches:['analytics'],coreSkills:['GA4'],sharedSkills:['GA4'],reasons:[],blockers:[],limitations:[]},job={id:'SOURCE-1',sourceId:'one',source:'Synthetic ATS',title:'Digital analyst',employer:'Synthetic employer',location:'Amsterdam',salary:'Unknown',url:'https://careers.example.test/jobs/one',description:'Synthetic GA4 requirements',readAt:'2026-10-04T08:00:00Z',availability:'Synthetic; unverified'};
const review:ReviewWorkflow={id:'HQ-W-new',job,createdAt:'2026-10-04T08:01:00Z',cvReadAt:'2026-10-04T08:00:00Z',receipts:[],draft:null,stage:'Analyst hold',managerDecision:'Needs review',tracker:null,currentRules:true,currentFit:fit};
const old={...review,id:'HQ-W-old',superseded:true,createdAt:'2026-09-30T07:00:01Z',job:{...job,readAt:'2026-09-30T07:00:00Z'}};
assert.equal(earliestDiscovery(job.id,job.url,[{...job,createdAt:review.createdAt},{...old.job,createdAt:old.createdAt},{id:'other',url:'https://example.test/other',readAt:'2026-01-01T00:00:00Z'}]),old.job.readAt);
item=collectJobs({...data,jobs:[]},{...state,workflows:[old,review]})[0];assert.equal(jobDateInfo(item,'found').date,'2026-09-30');assert.equal(jobDateInfo(item,'applied').date,'');assert(jobDateInfo(item,'found').source.includes('Earliest recorded'));assert.equal(item.review?.id,review.id);
const noOp=()=>{},dates=renderToStaticMarkup(<JobDateFilters basis="found" period="Custom range" from="2026-09-30" to="2026-09-01" onBasis={noOp} onPeriod={noOp} onFrom={noOp} onTo={noOp} onClear={noOp}/>);assert(dates.includes('Found on'));assert(dates.includes('Applied on'));assert(dates.includes('type="date"'));assert(dates.includes('aria-invalid="true"'));assert(dates.includes('start date must be on or before'));
const card=renderToStaticMarkup(<JobSummary item={collectJobs(data,state)[0]} onOpen={noOp}/>);assert(card.includes('Found 2026-09-30'));assert(card.includes('Applied 2026-10-02'));assert(!card.includes('Found 9/30/2026'));
const props={mode:'jobs' as const,data,state,refresh:async()=>{},sync:async()=>data,selected:'',group:'Applied' as const,onSelect:noOp,onGroup:noOp,onSettings:noOp,onOffice:noOp,onRecheck:noOp,reviewBusy:false,reviewNotice:'',reviewError:'',replay:false};
const view=renderToStaticMarkup(<DailyWorkspace {...props}/>);assert(view.includes('value="applied" selected'));assert(view.includes('Filter jobs by date'));assert(view.includes('Custom range'));assert(view.includes('Date missing'));
const detail=renderToStaticMarkup(<JobDetail {...props} item={collectJobs(data,state)[0]} onBack={noOp}/>);assert(detail.includes('Found on'));assert(detail.includes('source value: 9/30/2026'));assert(detail.includes('Applied on'));assert.equal(native.applied,'10/2/2026','Display normalization preserves Google optimistic expectations');
const css=readFileSync('app/daily.css','utf8');assert(css.includes('.job-date-controls input{min-height:44px'));assert(css.includes('.job-date-controls{display:grid;grid-template-columns:1fr 1fr'));
console.log('Job date checks passed: locale-aware native dates with unchanged source values, earliest HQ discoveries, Amsterdam day boundaries, inclusive/open ranges, invalid/missing dates, visible controls and mobile layout.');
