import {useEffect,useState,type FormEvent} from 'react';
import {Sparkles,Check,HelpCircle,TriangleAlert,Copy,ShieldCheck,ExternalLink,ListChecks} from 'lucide-react';
import type {ScoutState} from './scout';
import {safeUrl} from './data';
import './analyst-ai.css';
import {zone} from './zone';

export type AiReview={id:string;jobId:string;at:string;model:string;servedBy:string;fallback:boolean;scope:string;cvReadAt:string|null;verdict:'strong'|'plausible'|'stretch'|'unlikely';summary:string;strengths:{requirement:string;link?:'direct'|'related'|'inferred';vacancyQuote:string;cvQuote:string;reasoning:string}[];unverified:{requirement:string;reason:string}[];gaps:{requirement:string;vacancyQuote:string;importance:string;note:string;quoteVerified:boolean}[];ownerChecks:string[];seniority:string;letter:string;letterFlags:string[];interviewQuestions:string[];usage:null|{input:number;output:number;cacheRead:number;cacheWrite:number};limited?:boolean;vacancyChars?:number;seconds?:number;costUsd?:number|null};
export type ModelRun={startedAt:string;finishedAt:string|null;status:string;error:string|null;requested?:number;screened?:number;relevant?:number;possible?:number;unrelated?:number;missed?:number;skipped?:number;model?:string;costUsd?:number|null};
export type AiState={consentCurrent?:boolean;configured:boolean;enabled:boolean;model:string;scope:string;dailyLimit:number;usedToday:number;consentAt:string|null;models:Record<string,string>;scopes:Record<string,string>;version:string};
export type AiRun={startedAt:string;finishedAt:string|null;status:string;requested:number;assessed:number;reused:number;skipped:number;error:string|null};
const verdicts:Record<AiReview['verdict'],string>={strong:'Strong match',plausible:'Plausible match',stretch:'Stretch',unlikely:'Unlikely match'};
const stamp=(at:string|null)=>at?new Date(at).toLocaleString('en-GB',{timeZone:zone(),day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'not recorded';
export type Motivation={id:string;jobId:string;at:string;model:string;scope:string;company:{identified:boolean;about:string;facts:{fact:string;source:string}[]};language:string;motivation:string;angles:string[];avoid:string[];usedFacts:number[];searches:number;costUsd:number|null;excerpt:boolean};
async function send(action:'ai-review'|'ai-settings'|'vacancy-text'|'ai-screen'|'ai-motivation',body:object){
  const response=await fetch('/api/scout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...body}),signal:AbortSignal.timeout(60000)}),result=await response.json() as {error?:string;message?:string};
  if(!response.ok)throw new Error(result.error||'This action could not be completed.');
  return result.message||'Request accepted.';
}
const cost=(usd:number|null|undefined)=>typeof usd==='number'?' · about $'+usd.toFixed(2)+' in tokens at list prices':'';
// Today: shows that a search or screening is running, then what the last one did. Find jobs starts both.
export function ModelScout({state,refresh,locked,onSettings}:{state:ScoutState;refresh:()=>Promise<void>;locked:boolean;onSettings:()=>void}){
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  const ai=state.ai,screen=state.triageRun,found=state.runSummary,working=state.status==='running'&&!state.connectionError,screening=working&&screen?.status==='running',assessing=working&&state.aiRun?.status==='running',waiting=state.unscreened||0,ready=!!ai?.enabled&&!!ai.consentCurrent,spent=!!ai&&ai.usedToday>=ai.dailyLimit;
  async function start(){setBusy(true);setError('');try{await send('ai-screen',{});await refresh();}catch(e){setError(e instanceof Error?e.message:'The request could not be started.');await refresh();}finally{setBusy(false);}}
  if(!state.protected)return null;
  return <section className="model-scout" aria-label="Search and screening progress">
    {working?<div className="scout-progress" role="status" aria-live="polite"><div className="scout-progress-bar" aria-hidden="true"/>{!assessing&&<ol><li className={screening?'done':'active'}>{screening?<Check size={14}/>:<span>1</span>}Searching your sources</li><li className={screening?'active':''}><span>2</span>Screening by your CV</li></ol>}<p><strong>{state.task||'Working…'}</strong>This can take a few minutes. You can leave this page; the work carries on.</p></div>:<>
    {found&&<p className="quiet">Last search {stamp(found.at)}: {found.added} new {found.added===1?'discovery':'discoveries'}, {found.total} on your board{found.failed?' · '+found.failed+' of '+found.sources+' sources could not be read':''}.</p>}
    {screen&&screen.status!=='running'&&<p className={screen.status==='failed'||screen.error?'ai-warning':'quiet'}>{screen.status==='failed'?<><TriangleAlert size={15}/>Last screening failed: {screen.error}</>:<>Last screening {stamp(screen.finishedAt)}: {screen.screened} judged against your CV, {screen.relevant} relevant, {screen.possible} possible, {screen.unrelated} unrelated{screen.missed?', '+screen.missed+' without a verdict':''}{cost(screen.costUsd)}.{screen.error?' '+screen.error:''}</>}</p>}
    {!ready?<div className="model-scout-actions"><small><ListChecks size={14}/>{ai?.enabled?'Find jobs searches your sources. To have new jobs screened by your CV as well, confirm the model connection once in Settings.':'Find jobs searches your sources. Screening new jobs by your CV instead of fixed keywords needs the model connection.'}</small><button className="text-button" onClick={onSettings}>Open Settings</button></div>
     :waiting>0?<div className="model-scout-actions"><button className="subtle-button" disabled={locked||busy||spent} onClick={start}><ListChecks size={15}/>Screen {waiting} waiting by my CV</button><small>{spent?'The daily limit for model requests is reached; these wait until tomorrow or a higher limit in Settings.':'Found by the hourly check since your last screening. Find jobs screens them too.'}</small></div>
     :<p className="quiet">Find jobs searches your sources, then the Analyst screens what is new against your CV. Screening is a paid model request for every sixty discoveries.</p>}
    {error&&<p className="connection-feedback error" role="alert">{error}</p>}</>}
  </section>;
}
export const latestAssessment=(state:ScoutState,jobId:string)=>(state.aiReviews||[]).filter(r=>r.jobId===jobId).at(-1);

// Advisory only: this panel never changes CV screening, the saved review or the tracker.
// The motivation part of an application: what the employer does, found on the public web with its sources, and a few sentences that tie the CV to it. A draft to rewrite in your own voice, never sent anywhere.
export function MotivationDraft({jobId,state,refresh,locked,onSettings}:{jobId:string;state:ScoutState;refresh:()=>Promise<void>;locked:boolean;onSettings:()=>void}){
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[copied,setCopied]=useState(false);
  const ai=state.ai,draft=(state.motivations||[]).find(m=>m.jobId===jobId),run=state.motivationRun,running=run?.status==='running'&&state.status==='running',mine=run?.jobId===jobId,left=ai?ai.dailyLimit-ai.usedToday:0,ready=!!ai?.enabled&&!!ai.consentCurrent;
  useEffect(()=>{setError('');setCopied(false);},[jobId,draft?.id]);
  async function start(){setBusy(true);setError('');try{await send('ai-motivation',{jobId});await refresh();}catch(e){setError(e instanceof Error?e.message:'The request could not be started.');await refresh();}finally{setBusy(false);}}
  if(!state.protected||!ai)return null;
  return <section className="ai-assessment motivation-draft" aria-label="Motivation for this application">
    <header><p className="eyebrow">ANALYST · MOTIVATION</p><h3>Why this employer?</h3></header>
    {draft?<>
      <div className="motivation-text"><p>{draft.motivation}</p><button className="subtle-button" onClick={async()=>{try{await navigator.clipboard.writeText(draft.motivation);setCopied(true);}catch{setError('Copy is unavailable. Select the text to copy it.');}}}><Copy size={15}/>{copied?'Copied':'Copy'}</button></div>
      <p className="quiet">A draft written by the model from your CV material{draft.excerpt?' and a short excerpt of the vacancy':' and the vacancy text'}. Rewrite it in your own words and check every statement before using it. Nothing is sent to the employer.</p>
      {draft.angles.length>0&&<><h4>What to emphasise</h4><ul>{draft.angles.map((a,i)=><li key={i}>{a}</li>)}</ul></>}
      {draft.avoid.length>0&&<><h4>Do not claim</h4><ul>{draft.avoid.map((a,i)=><li key={i}>{a}</li>)}</ul></>}
      <h4>About the employer, from the web</h4>
      {draft.company.facts.length?<><p className="quiet">{draft.company.about}</p><ol className="motivation-facts">{draft.company.facts.map((f,i)=><li key={i} className={draft.usedFacts.includes(i+1)?'used':''}>{f.fact} <a href={f.source} target="_blank" rel="noreferrer">source <ExternalLink size={12}/></a>{draft.usedFacts.includes(i+1)&&<small> · used in the draft</small>}</li>)}</ol><p className="quiet">Found by the model in {draft.searches} web search{draft.searches===1?'':'es'}. HQ did not check these pages; open a source before you rely on a fact.</p></>:<p className="ai-warning"><TriangleAlert size={15}/>{draft.company.identified?'No usable facts were recorded.':'The model could not identify this employer with confidence on the web'}, so the draft rests on your CV and the vacancy only.</p>}
      <footer><span>{ai.models[draft.model]||draft.model}</span><span>Drafted {stamp(draft.at)}</span>{typeof draft.costUsd==='number'&&<span>About ${draft.costUsd.toFixed(2)} in tokens and search fees at list prices</span>}</footer>
    </>:<p>The Analyst can look this employer up on the web and suggest a few sentences on why you want to work there, tied to your CV.</p>}
    {error&&<p className="connection-feedback error" role="alert">{error}</p>}{!error&&mine&&run?.status==='failed'&&run.error&&<p className="connection-feedback error" role="alert">Last attempt failed: {run.error}</p>}
    {ready?<div className="ai-actions"><button className={draft?'subtle-button':'primary-button'} disabled={locked||busy||running||left<2} onClick={start}><Sparkles size={15}/>{running&&mine?'Researching and drafting…':draft?'Research and draft again':'Research the employer & draft a motivation'}</button><small>Uses two of your daily model requests ({Math.max(0,left)} left today). The web research is given the employer name, role and location only. The draft request sends the recorded vacancy text and {ai.scope==='cv'?'the professional text of your CV, without contact lines,':'your retained CV evidence'} to Anthropic. Web searches are billed by Anthropic on top of tokens.</small></div>:<div className="ai-actions"><button className="subtle-button" onClick={onSettings}>Connect the model in Settings</button></div>}
  </section>;
}
export default function AnalystAssessment({jobId,state,refresh,locked,onSettings}:{jobId:string;state:ScoutState;refresh:()=>Promise<void>;locked:boolean;onSettings:()=>void}){
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[copied,setCopied]=useState(false),[text,setText]=useState('');
  const ai=state.ai,review=latestAssessment(state,jobId),run=state.aiRun,running=run?.status==='running',spent=!!ai&&ai.usedToday>=ai.dailyLimit,job=state.results.find(j=>j.id===jobId),excerpt=job?.completeness==='Aggregator excerpt',original=safeUrl(job?.url||'');
  useEffect(()=>{setError('');setNotice('');setCopied(false);setText('');},[jobId]);
  // A finished assessment replaces the "requested" notice.
  useEffect(()=>{setNotice('');setCopied(false);},[review?.id]);
  async function saveText(e:FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{setNotice(await send('vacancy-text',{jobId,description:text}));setText('');await refresh();}catch(e){setError(e instanceof Error?e.message:'The vacancy text could not be saved.');}finally{setBusy(false);}}
  async function assess(){setBusy(true);setError('');setNotice('');try{setNotice(await send('ai-review',{jobId,force:!!review}));await refresh();}catch(e){setError(e instanceof Error?e.message:'Assessment unavailable.');await refresh();}finally{setBusy(false);}}
  return <section className="ai-assessment" aria-label="Model-based assessment"><header><Sparkles size={19}/><h3>Analyst assessment</h3><span className="ai-badge">Model-based · advisory</span></header>
    {!ai?.enabled?<><p>A language model can read this vacancy against your CV and explain the match, with every strength quoted from both texts. It is switched off, and nothing is sent anywhere until you connect it.</p><button className="subtle-button" onClick={onSettings}>Set up in Settings</button></>:<>
    {review?<>
      <div className="ai-verdict"><span className={'ai-verdict-chip '+review.verdict}>{verdicts[review.verdict]}</span><p>{review.summary}</p></div>
      {review.limited&&<p className="ai-warning"><TriangleAlert size={15}/>Based on a {review.vacancyChars}-character source excerpt, not the full vacancy. Treat this verdict as provisional.</p>}
      <h4>Evidence for the match</h4>
      {review.strengths.length?<ul className="ai-evidence">{review.strengths.map((s,i)=><li key={i}>{s.link&&s.link!=='direct'?<span className="ai-icon" aria-hidden="true"><HelpCircle size={16}/></span>:<span className="ai-icon documented" aria-hidden="true"><Check size={16}/></span>}<div><strong>{s.requirement}{s.link&&<span className={'ai-importance ai-link '+s.link}>{s.link}</span>}</strong><p><b>Vacancy</b>“{s.vacancyQuote}”</p><p><b>Your CV</b>“{s.cvQuote}”</p><small>{s.reasoning}</small></div></li>)}</ul>:<p className="quiet">No strength survived the quote check. Read the vacancy yourself before relying on this assessment.</p>}
      {review.unverified.length>0&&<p className="ai-warning"><TriangleAlert size={15}/>{review.unverified.length} suggested {review.unverified.length===1?'strength was':'strengths were'} discarded because the quoted wording was not found in your CV material or the recorded vacancy.</p>}
      <h4>Gaps to check</h4>
      {review.gaps.length?<ul className="ai-evidence">{review.gaps.map((g,i)=><li key={i}><span className="ai-icon" aria-hidden="true"><HelpCircle size={16}/></span><div><strong>{g.requirement}<span className="ai-importance">{g.importance}</span></strong>{g.vacancyQuote&&<p><b>Vacancy</b>“{g.vacancyQuote}”{!g.quoteVerified&&' · this wording was not found in the recorded vacancy'}</p>}<small>{g.note}</small></div></li>)}</ul>:<p className="quiet">The model listed no gaps. That is not proof that every requirement is met.</p>}
      <h4>Seniority</h4><p>{review.seniority}</p>
      {review.ownerChecks.length>0&&<><h4>Only you can confirm</h4><ul className="ai-plain">{review.ownerChecks.map((c,i)=><li key={i}>{c}</li>)}</ul></>}
      <details className="ai-draft"><summary>Letter draft &amp; interview questions</summary><p className="quiet">Written by the model from your CV material. It is a draft: check every statement before using it. Nothing is sent to an employer.</p>{review.letterFlags.length>0&&<p className="ai-warning"><TriangleAlert size={15}/>Check these figures; they do not appear in your CV material or the vacancy: {review.letterFlags.join(', ')}</p>}<div className="ai-draft-heading"><h4>Letter draft</h4><button className="subtle-button" onClick={async()=>{try{await navigator.clipboard.writeText(review.letter);setCopied(true);}catch{setError('Copy is unavailable. Select the draft text to copy it.');}}}><Copy size={15}/>{copied?'Copied':'Copy draft'}</button></div><pre>{review.letter}</pre><h4>Questions to ask</h4><ul className="ai-plain">{review.interviewQuestions.map((q,i)=><li key={i}>{q}</li>)}</ul></details>
      <footer><span>{ai.models[review.servedBy]||review.servedBy}{review.fallback?' · answered by a substitute model after a safety check declined':''}</span><span>Assessed {stamp(review.at)}</span><span>CV read {stamp(review.cvReadAt)}</span><span>{ai.scopes[review.scope]||review.scope}</span>{typeof review.costUsd==='number'&&<span>About ${review.costUsd.toFixed(2)} at list prices</span>}{!!review.seconds&&<span>{review.seconds} s</span>}</footer>
    </>:<p>No model-based assessment is recorded for this vacancy yet.</p>}
    {error&&<p className="connection-feedback error" role="alert">{error}</p>}{!error&&run?.status==='failed'&&run.error&&<p className="connection-feedback error" role="alert">Last assessment failed: {run.error}</p>}{!error&&run?.status==='completed'&&run.error&&<p className="ai-warning"><TriangleAlert size={15}/>{run.error}</p>}{notice&&!running&&!error&&<p className="quiet" role="status">{notice}</p>}
    {excerpt&&job&&<p className="ai-warning"><TriangleAlert size={15}/>Scout holds only a {job.description.length}-character excerpt of this vacancy from {job.source}. Add the full text below so the assessment can read the real requirements.</p>}
    {job?.ownerTextAt&&<p className="quiet">Full vacancy text provided by you on {stamp(job.ownerTextAt)}. It is not independently verified.</p>}
    {job&&(excerpt||job.ownerTextAt)&&<details className="ai-draft ai-text"><summary>{job.ownerTextAt?'Replace the vacancy text':'Add the full vacancy text'}</summary><p className="quiet">Open the original vacancy, copy its description and requirements and paste them here. HQ does not fetch the page. The text is stored privately, replaces the excerpt in reviews and assessments, and is not written to your tracker.</p>{original&&<a className="text-button" href={original} target="_blank" rel="noreferrer">Open the original vacancy <ExternalLink size={14}/></a>}<form onSubmit={saveText}><label className="connection-field">Vacancy text<textarea rows={8} value={text} onChange={e=>setText(e.target.value)} minLength={200} maxLength={18000} required disabled={locked||busy||running}/></label><button className="subtle-button" disabled={locked||busy||running}>Save vacancy text</button></form></details>}
    <div className="ai-actions"><button className={review?'subtle-button':'primary-button'} disabled={locked||busy||running||spent} onClick={assess}><Sparkles size={15}/>{running?'Analyst is assessing…':review?'Assess again':'Get a full assessment'}</button><small>{ai.usedToday} of {ai.dailyLimit} assessments used today{spent?' · daily limit reached':''}. Sends the recorded vacancy text and {ai.scope==='cv'?'the professional text of your CV, without contact lines,':'your retained CV evidence'} to Anthropic. CV screening and your tracker are not changed.</small></div></>}
  </section>;
}

export function AnalystAiSettings({state,refresh}:{state:ScoutState;refresh:()=>Promise<void>}){
  const ai=state.ai,[apiKey,setApiKey]=useState(''),[model,setModel]=useState(ai?.model||'claude-opus-5-5'),[scope,setScope]=useState(ai?.scope||'evidence'),[limit,setLimit]=useState(ai?.dailyLimit||20),[enabled,setEnabled]=useState(!!ai?.enabled),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  useEffect(()=>{if(ai){setModel(ai.model);setScope(ai.scope);setLimit(ai.dailyLimit);setEnabled(ai.enabled);}},[ai?.model,ai?.scope,ai?.dailyLimit,ai?.enabled]);
  const locked=!state.protected||!!state.connectionError||busy||state.status==='running';
  async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{setNotice(await send('ai-settings',{apiKey,model,scope,dailyLimit:limit,enabled,consent}));setApiKey('');setConsent(false);await refresh();}catch(e){setError(e instanceof Error?e.message:'Settings could not be saved.');}finally{setBusy(false);}}
  return <section className="scout-view ai-settings"><article className="source-card"><header><Sparkles size={23}/><div><p className="eyebrow">MODEL CONNECTION · OPTIONAL</p><h3>CV screening &amp; assessments</h3></div><span className="badge">{ai?.enabled?'On':ai?.configured?'Key saved · off':'Not connected'}</span></header>
    <p>Lets the Analyst screen discoveries by your CV instead of fixed keywords, and gives a full assessment of one vacancy: a verdict, quoted evidence, gaps, a letter draft and interview questions. You start each of these yourself. Saving to your tracker and applying work exactly as before.</p>{ai?.enabled&&!ai.consentCurrent&&<p className="ai-warning"><TriangleAlert size={15}/>Screening by your CV is new. Tick the consent line and save once more to allow it; assessments keep working meanwhile.</p>}
    <div className="evidence-note"><ShieldCheck size={18}/><p>Switching this on changes one privacy rule: when you request an assessment or a screening, the CV material you choose below is sent to Anthropic's API, together with the vacancy texts being judged. Lines containing an email address, phone number, link, postal address or birth date are removed first; your name and employer names stay if they appear in the CV. Nothing is sent while this is off, during Scout searches or in the background.</p></div>
    {error&&<div className="connection-feedback error" role="alert">{error}</div>}{notice&&<div className="connection-feedback success" role="status"><Check size={17}/>{notice}</div>}
    <form onSubmit={save}><label className="connection-field">Anthropic API key<input type="password" autoComplete="new-password" value={apiKey} onChange={e=>setApiKey(e.target.value)} required={!ai?.configured} placeholder={ai?.configured?'Saved · leave blank to keep':'Enter directly here; never in chat'} disabled={locked}/><small>Created in the Claude Console and billed separately from any Claude subscription. Stored encrypted with your other private settings and never shown again.</small></label>
    <div className="scout-search-fields"><label className="connection-field">Model<select value={model} onChange={e=>setModel(e.target.value)} disabled={locked}>{Object.entries(ai?.models||{'claude-opus-5-5':'Claude Opus 5.5'}).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label className="connection-field">Daily limit<input type="number" min={1} max={100} value={limit} onChange={e=>setLimit(Number(e.target.value))} disabled={locked}/></label></div>
    <label className="connection-field">CV material that may be sent<select value={scope} onChange={e=>{setScope(e.target.value);setConsent(false);}} disabled={locked}>{Object.entries(ai?.scopes||{evidence:'Retained CV evidence only'}).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><small>{scope==='cv'?'Your CV is read again for each request and its professional text is sent without the contact lines. The full text is not stored by HQ.':'Only the skill names and the bounded sentences HQ already retains are sent. The assessment sees less of your experience.'}</small></label>
    <label className="ai-check"><input type="checkbox" checked={enabled} onChange={e=>{setEnabled(e.target.checked);setConsent(false);}} disabled={locked}/>Allow the model tasks I start</label>
    {enabled&&<label className="ai-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} disabled={locked}/>I agree that the CV material selected above and the vacancy texts are sent to Anthropic when I start an assessment or a screening.</label>}
    <button className="subtle-button" disabled={locked||enabled&&!consent}>Save model connection <Check size={15}/></button></form>
    <p className="quiet">{ai?`${ai.usedToday} of ${ai.dailyLimit} assessments used today. `:''}Each assessment is one paid API request; identical vacancy and CV inputs reuse the saved result.</p>
    <a href="https://platform.claude.com/" className="text-button" target="_blank" rel="noreferrer">Claude Console · create an API key <ExternalLink size={14}/></a></article></section>;
}
