import {normalizeActivityDate,activityDay} from './activity-dates';
import {sheetCalendarDate} from './job-dates';
import {zone} from './zone';
export type Job={id:string;employer:string;role:string;location:string;status:string;salary:string;language:string;url:string;found:string;applied:string;foundDate?:string;appliedDate?:string;verified:string;next:string;due:string;notes:string;requirements:string;fit:string;gaps:string;source:string;approval:string;gate:string;confirmation?:string};
export type Activity={id:string;recordId:string;date:string;type:string;actor:string;details:string;evidence:string;next:string;due:string;category:'administrative'|'employer'|'candidate'|'other';sourceDate?:string;agentId?:string;handoff?:[string,string]};
export type Snapshot={mode:'demo'|'synced';jobs:Job[];events:Activity[];syncedAt:string|null;fetchedAt:string;stale:boolean;error:string|null;controls:Record<string,string>;overview:Record<string,string>[];source:string;dateWarnings?:number};
// Three roles, one per stage of the owner's journey: find, judge, keep the pipeline true.
export const agents=[
{id:'00',name:'Tracker',recordedName:'Recruitment Coordinator',short:'Tracker',discipline:'PIPELINE',color:'#d8b885',position:[0,0,-3.8] as [number,number,number],role:'Keeps your pipeline true: saves the jobs you choose to the database and records the applications and status changes you confirm.',authority:'Writes to the tracker only through the database, one owner-confirmed change at a time. It never applies, sends messages or changes an outcome on its own.',icon:'◎'},
{id:'01',name:'Scout',recordedName:'Job Scout',short:'Scout',discipline:'DISCOVERY',color:'#83c9ce',position:[-5.5,0,-1.4] as [number,number,number],role:'Searches your sources for vacancies and removes duplicates.',authority:'Read-only role. Vacancy availability requires documented verification.',icon:'⌕'},
{id:'02',name:'Analyst',recordedName:'Job Analyst',short:'Analyst',discipline:'EVALUATION',color:'#a7a0db',position:[-5.5,0,3.2] as [number,number,number],role:'Judges each vacancy against your CV, and prepares the letter draft, CV points and interview questions for the ones worth pursuing.',authority:'Read-only role. Fit information is shown only when documented; this interface cannot submit applications.',icon:'◈'}];
// The preparation and follow-up steps used to be separate roles (03, 04). Their records and task steps now belong to the Analyst.
export const roleOf=(id:string|null|undefined)=>id==='03'||id==='04'?'02':id||'';
export const agentName=(id:string|null|undefined)=>agents.find(a=>a.id===roleOf(id))?.name||'Unknown role';
const empty:Job={id:'',employer:'',role:'',location:'Unknown',status:'Discovered',salary:'Unknown',language:'Unknown',url:'',found:'',applied:'',verified:'',next:'Not documented',due:'',notes:'',requirements:'Not documented',fit:'Not documented',gaps:'Not documented',source:'Demo dataset',approval:'Pending review',gate:'Observation only'};
const demoJobs:Job[]=[
{...empty,id:'DEMO-001',employer:'Northstar Studio',role:'Digital Analytics Lead',location:'Amsterdam · Hybrid',status:'Interview',salary:'€65,000–€78,000',language:'English',found:'2026-09-25',applied:'2026-09-26',next:'Review the recorded interview invitation',notes:'Fictional vacancy for exploring the headquarters.',requirements:'Analytics strategy, GA4, stakeholder collaboration and experimentation.',fit:'Documented demo fit: web analytics and cross-functional delivery.',gaps:'Demo gap: team leadership scope to clarify.'},
{...empty,id:'DEMO-002',employer:'Forma Collective',role:'Senior CRO Specialist',location:'Utrecht · Hybrid',status:'Applied',language:'Dutch / English',found:'2026-09-26',applied:'2026-09-28',next:'Await a documented employer response',requirements:'Experiment design, conversion analysis and customer journey optimisation.',fit:'Documented demo fit: experimentation and digital optimisation.'},
{...empty,id:'DEMO-003',employer:'Aperture Labs',role:'Product Owner · Data',location:'Rotterdam · Hybrid',status:'Review',salary:'€60,000–€72,000',language:'English',found:'2026-09-28',next:'Review the documented fit and language requirements',requirements:'Data product roadmaps, backlog ownership and stakeholder alignment.',fit:'Documented demo fit: analytics delivery and stakeholder alignment.',gaps:'Demo gap: formal product ownership experience.'},
{...empty,id:'DEMO-004',employer:'Meridian Commerce',role:'E-commerce Manager',location:'Remote · Netherlands',status:'Discovered',found:'2026-09-29',next:'Verify the original vacancy and requirements',notes:'Availability has not been verified.'},
{...empty,id:'DEMO-005',employer:'Vela Systems',role:'Web Platform Specialist',location:'Amersfoort',status:'Preparing',salary:'€58,000–€68,000',language:'English',found:'2026-09-28',next:'Review the draft application material',fit:'Documented demo fit: web platforms and digital delivery.',requirements:'Web operations, technical SEO and platform governance.'},
{...empty,id:'DEMO-006',employer:'Fieldwork Digital',role:'Growth Analytics Consultant',location:'Amsterdam',status:'Closed',found:'2026-09-24',next:'None — posting closed',notes:'Fictional closed vacancy; no submission controls.'},
{...empty,id:'DEMO-007',employer:'Atelier Eleven',role:'Digital Optimisation Lead',location:'Den Haag',status:'Rejected',found:'2026-09-22',applied:'2026-09-24',next:'None — administratively archived',notes:'Demo administrative classification requested by the candidate. This is not employer rejection evidence.'}];
const demoEvents:Activity[]=[
{id:'DEMO-E001',recordId:'DEMO-004',date:'2026-09-29T08:10:00+02:00',type:'Discovery',actor:'01 — Job Scout',details:'Fictional vacancy recorded for later availability verification.',evidence:'Synthetic demonstration event',next:'Verify original vacancy',due:'',category:'administrative',agentId:'01'},
{id:'DEMO-E002',recordId:'DEMO-003',date:'2026-09-29T09:20:00+02:00',type:'Handoff',actor:'01 — Job Scout',details:'Demo evidence records a handoff from Scout to Analyst for a fit review.',evidence:'Synthetic event; explicit 01 → 02 handoff',next:'Review documented fit',due:'',category:'administrative',agentId:'02',handoff:['01','02']},
{id:'DEMO-E003',recordId:'DEMO-002',date:'2026-09-29T11:45:00+02:00',type:'Confirmation',actor:'Forma Collective',details:'Fictional application receipt recorded. No employer outcome is implied.',evidence:'Synthetic employer receipt',next:'Await response',due:'',category:'employer'},
{id:'DEMO-E004',recordId:'DEMO-007',date:'2026-09-29T14:05:00+02:00',type:'Administrative status change',actor:'Candidate',details:'Candidate-directed archive classification. Not an employer rejection.',evidence:'Synthetic candidate instruction',next:'None',due:'',category:'administrative',agentId:'00'},
{id:'DEMO-E005',recordId:'DEMO-001',date:'2026-09-30T10:30:00+02:00',type:'Interview invitation',actor:'Northstar Studio',details:'Fictional invitation recorded for candidate review. Attendance and outcome unknown.',evidence:'Synthetic employer correspondence',next:'Review invitation',due:'',category:'employer'},
{id:'DEMO-E006',recordId:'DEMO-005',date:'2026-09-30T11:00:00+02:00',type:'Handoff',actor:'02 — Job Analyst',details:'Demo evidence records an Analyst to Application Specialist handoff for draft preparation.',evidence:'Synthetic event; explicit 02 → 03 handoff',next:'Review draft',due:'',category:'administrative',agentId:'03',handoff:['02','03']}];
export function makeDemo():Snapshot{return {mode:'demo',jobs:demoJobs,events:demoEvents,syncedAt:null,fetchedAt:new Date().toISOString(),stale:false,error:null,controls:{},overview:[],source:'Isolated fictional dataset · no tracker writes'};}
// Where the records live, for labels.
export const recordsHome=(_data?:unknown)=>'the database';
export function safeUrl(value:string){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;}}
export function classifyEvent(type:string,actor:string,details:string):Activity['category']{const all=(type+' '+details).toLowerCase();if(/administrativ|user.directed|candidate.directed|not.*employer|not newly.*rejection|status.change|reconcil|audit|classification/.test(all))return 'administrative';if(/^(candidate|owner|user|me)$/i.test(actor.trim()))return 'candidate';if(/confirmation|receipt|email received|interview|employer|response|rejection|offer/.test(type.toLowerCase()))return 'employer';return 'other';}
export function rowsToObjects(rows:unknown[][]):Record<string,string>[]{const headers=(rows[0]??[]).map(String);return rows.slice(1).filter(r=>r.some(v=>v!==null&&v!=='')).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]==null?'':String(r[i])])));}
export function noteExcerpt(notes:string,label:string){const labels:Record<string,string>={fit:'(?:CV links|Transferable)',gaps:'(?:Gaps|Significant gaps|Check specific gaps)',requirements:'Requirements'};const match=notes.match(new RegExp(labels[label]+':\\s*([^\\n]*?)(?:\\.\\s|$)','i'));return match?.[1]?('From source notes: '+match[1]):'Not separately documented — see source notes';}
export function mapSheetData(valueRanges:{values?:unknown[][]}[],dates={locale:'en_US',timeZone:zone()}):Pick<Snapshot,'jobs'|'events'|'controls'|'overview'|'dateWarnings'>{
const tracker=valueRanges[0]?.values??[],log=valueRanges[1]?.values??[];
for(const h of ['Record ID','Employer','Role title','Status'])if(!tracker[0]?.includes(h))throw new Error('Job Tracker schema changed: missing '+h);
for(const h of ['Event ID','Record ID','Event date','Event type'])if(!log[0]?.includes(h))throw new Error('Activity Log schema changed: missing '+h);
const ids=new Set<string>();
const jobs=rowsToObjects(tracker).filter(r=>r['Record ID']).map(r=>{const id=r['Record ID'];if(ids.has(id))throw new Error('Duplicate Record ID; sync stopped.');ids.add(id);return {...empty,id,employer:r.Employer,role:r['Role title'],location:r.Location||'Unknown',status:r.Status||'Unknown',salary:r['Salary / range']||'Unknown',language:r.Language||'Unknown',url:r['Original job URL']||r['Official employer URL']||'',found:r['Date found'],applied:r['Applied on'],foundDate:sheetCalendarDate(r['Date found'],dates.locale,dates.timeZone),appliedDate:sheetCalendarDate(r['Applied on'],dates.locale,dates.timeZone),confirmation:r['Submission confirmation / ref']||'',verified:r['Last verified'],next:r['Next action']||'Not documented',due:r['Follow-up due'],notes:r.Notes,source:r['Source / agency'],approval:r.Approval,gate:r['Submission gate (auto)']||'Unknown',requirements:noteExcerpt(r.Notes||'','requirements'),fit:noteExcerpt(r.Notes||'','fit'),gaps:noteExcerpt(r.Notes||'','gaps')};});
const eventIds=new Set<string>();
const events:Activity[]=rowsToObjects(log).filter(r=>r['Event ID']).map(r=>{if(eventIds.has(r['Event ID']))throw new Error('Duplicate Event ID; sync stopped.');eventIds.add(r['Event ID']);return {id:r['Event ID'],recordId:r['Record ID'],date:normalizeActivityDate(r['Event date'],dates.locale,dates.timeZone),sourceDate:r['Event date'],type:r['Event type'],actor:r['Contact / actor'],details:r['Details / outcome'],evidence:r['Evidence / URL'],next:r['Next action'],due:r['Next action due'],category:classifyEvent(r['Event type'],r['Contact / actor'],r['Details / outcome']),agentId:agents.find(a=>[a.name,a.recordedName].some(name=>r['Contact / actor']===name||r['Contact / actor'].startsWith(a.id+' — '+name)))?.id};});
return {jobs,events,dateWarnings:events.filter(e=>!activityDay(e.date)).length,controls:Object.fromEntries((valueRanges[3]?.values??[]).filter(r=>r[0]&&r[1]).map(r=>[String(r[0]),String(r[1])])),overview:rowsToObjects(valueRanges[2]?.values??[])};
}
export function buildBriefing(data:Snapshot){const today=new Intl.DateTimeFormat('en-CA',{timeZone:zone(),year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const day=data.mode==='demo'?'2026-09-30':today,daily=data.events.filter(e=>activityDay(e.date)===day);return {day,discoveries:daily.filter(e=>/discover|vacancy found/i.test(e.type)).length,applications:daily.filter(e=>/submitted|application sent/i.test(e.type)&&!(/historical|reconstruct|not.*newly/i.test(e.details))).length,responses:daily.filter(e=>e.category==='employer').length,administrative:daily.filter(e=>e.category==='administrative').length,attention:data.jobs.filter(j=>j.next!=='Not documented'&&!/^none|await/i.test(j.next)&&!['Closed','Rejected','Withdrawn'].includes(j.status))};}


