import {useRef,useState} from 'react';
import type {JobItem} from './daily-model';
import type {ScoutState} from './scout';
import {ownerStatusFor,savePlanningStatus} from './owner-status-model';
import {zone} from './zone';
export default function DiscoveryStatus({item,state,replay,refresh}:{item:JobItem;state:ScoutState;replay:boolean;refresh:()=>Promise<void>}){
 const source=item.discovery||item.review?.job,saved=ownerStatusFor(state,source?.url||'',source?.id||''),[open,setOpen]=useState(false),[status,setStatus]=useState(saved?.status||'Discovered'),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),pending=useRef<{requestId:string;body:object}|null>(null),running=useRef(false);
 const locked=!source||!state.protected||!!state.connectionError||state.status==='running'||replay||busy;
 async function save(){if(!source||locked||running.current)return;running.current=true;setBusy(true);setError('');pending.current??={requestId:'HQ-P-'+crypto.randomUUID(),body:{jobId:source.id,status,reason:reason.trim(),expectedId:saved?.id||'',confirmStatus:true}};try{const result=await savePlanningStatus({...pending.current.body,requestId:pending.current.requestId});pending.current=null;setNotice(result.status+' saved privately in HQ.');await refresh();}catch(e){setError(e instanceof Error?e.message:'Planning status unavailable.');}finally{running.current=false;setBusy(false);}}
 return <section className="job-status-editor" aria-label="Edit discovery status"><button className="text-button" onClick={()=>setOpen(v=>!v)} aria-expanded={open}>Status: {saved?.status||'Discovered'} · change</button>{open&&<><p>This planning choice is saved in HQ beside the discovery. Tracker updates become available after you save an eligible review. Applied uses the confirmed application control above.</p>{error&&<p className="connection-feedback error" role="alert">{error}</p>}{notice&&<p className="connection-feedback success" role="status">{notice}</p>}<form onSubmit={e=>{e.preventDefault();save();}}><label className="connection-field">Planning status<select aria-label="Discovery planning status" value={status} disabled={locked||!!pending.current} onChange={e=>setStatus(e.target.value)}>{['Discovered','Researching','Shortlisted','Preparing','Ready to apply','On hold'].map(s=><option key={s}>{s}</option>)}</select></label><label className="connection-field">Reason<textarea required minLength={3} maxLength={500} value={reason} disabled={locked||!!pending.current} onChange={e=>setReason(e.target.value)} rows={2}/></label><button className="primary-button" disabled={locked||(!pending.current&&(status===(saved?.status||'Discovered')||reason.trim().length<3))}>{busy?'Saving…':pending.current?'Retry same decision':'Save planning status'}</button></form>{saved&&<p>{saved.reason} · {new Date(saved.at).toLocaleString('en-GB',{timeZone:zone()})}</p>}{saved?.history.map(h=><p key={h.id}>{h.status} · {h.reason} · {new Date(h.at).toLocaleString('en-GB',{timeZone:zone()})}</p>)}</>}</section>;
}
