import {Database,ArrowRight,Info} from 'lucide-react';
import type {Snapshot} from './data';
import type {ScoutState} from './scout';
import {collectJobs} from './daily-model';
import {zone} from './zone';
export default function EvidenceSources({data,state,onOpen}:{data:Snapshot;state:ScoutState;onOpen:()=>void}){
 const items=collectJobs(data,state),demo=data.mode==='demo'&&!state.protected;
 return <section className="evidence-sources" aria-label="Your unified jobs board"><button className="unified-board-link" onClick={onOpen}><Database size={23}/><span><strong>{items.length} {demo?'demo jobs':'jobs'} on your board</strong><small>Scout findings, agent advice and tracker status · open any job for the full record{data.stale?' · tracker data is stale':''}{state.connectionError?' · Scout data is stale':''}</small></span><ArrowRight size={20}/></button><details><summary><Info size={14}/>Sources &amp; connection details</summary><p>{data.mode==='synced'?data.jobs.length+' saved tracker records':demo?'Demo tracker records':'Tracker not connected'} · {data.events.length} recorded events · {state.protected?state.results.length:0} Scout discoveries{!state.protected?' · Scout not connected':''}. Matching vacancy links and verified record IDs share one job view. A discovery keeps its source ID until you choose to save an eligible review to your tracker. Existing native IDs and history are preserved.</p><p>Last Scout check: {state.lastSuccess?new Date(state.lastSuccess).toLocaleString('en-GB',{timeZone:zone()}):'Not recorded'}.</p><p>HQ does not read the Daily Coordinator chat. Paste its report below to check for missing jobs. Scout checks up to six phrases, two pages and 50 listings per page on Find jobs. Hourly checks rotate within the daily limit. Search coverage is bounded; LinkedIn and Indeed use owner imports. A tracker change does not establish that an agent is running.</p>{!!data.dateWarnings&&<p>{data.dateWarnings} event dates need checking; their source values remain in history.</p>}</details></section>;
}
