import {useRef,useState} from 'react';
import {Check,X,RotateCcw,Link2} from 'lucide-react';
import {recordsHome,type Snapshot} from './data';
import type {ScoutState} from './scout';
import {canSaveDiscovery,applicationRecorded,type JobItem} from './daily-model';
import ApplicationRecord,{amsterdamToday,canMarkApplied} from './application-record';
import {ownerFeedbackFor,requestOwnerFeedback,recordDiscoveryApplication,type DiscoveryApplicationAttempt} from './job-decisions-model';
import './job-decisions.css';
import {zone} from './zone';
export default function JobDecisions({item,data,state,replay,refresh,sync}:{item:JobItem;data:Snapshot;state:ScoutState;replay:boolean;refresh:()=>Promise<void>;sync:()=>Promise<Snapshot|undefined>}){
 const feedback=ownerFeedbackFor(state,item.job?.url||item.discovery?.url||item.review?.job.url||'',item.job?.id||item.discovery?.id||item.review?.job.id||''),[choice,setChoice]=useState<'applied'|'not-fit'|null>(null),[reason,setReason]=useState('Role / responsibilities'),[note,setNote]=useState(''),[date,setDate]=useState(amsterdamToday),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [target,setTarget]=useState(''),[sure,setSure]=useState(false);
 const inFlight=useRef(false),request=useRef<{id:string;body:string}|null>(null),application=useRef<DiscoveryApplicationAttempt|null>(null);
 const real=!!item.review||!!item.discovery||data.mode==='synced',locked=!real||!state.protected||!!state.connectionError||replay||state.status==='running'||busy;
 const applied=!!item.job&&applicationRecorded(item.job),canApply=!locked&&data.mode==='synced'&&!data.stale&&(item.job?canMarkApplied(item.job):!!(item.review||item.discovery)),overrides=!item.job&&!(item.review&&(canSaveDiscovery(item.review)||!!item.review.tracker));
 async function decide(decision:'not-fit'|'review'){if(locked||inFlight.current)return;inFlight.current=true;setBusy(true);setError('');setNotice('');const body={...(item.job?{recordId:item.job.id}:{jobId:item.discovery?.id||item.review!.job.id}),decision,reason:decision==='not-fit'?[reason,note.trim()].filter(Boolean).join(' · '):'',expectedId:feedback?.id||''},serialized=JSON.stringify(body);if(request.current?.body!==serialized)request.current={id:'HQ-F-'+crypto.randomUUID(),body:serialized};
  try{const saved=await requestOwnerFeedback({...body,requestId:request.current.id});setNotice(saved.decision==='not-fit'?'Your preference is saved in HQ. tracker status and agent advice are unchanged.':'Returned to review.');request.current=null;setChoice(null);await refresh();}catch(e){setError(e instanceof Error?e.message:'Preference not saved.');}finally{inFlight.current=false;setBusy(false);}}
 // The same vacancy posted in two places: tie this discovery to the job already on the board, or undo that. Jobs of the same employer come first in the list.
 const discoveryId=!item.job?item.discovery?.id||item.review?.job.id||'':'',same=(a:string,b:string)=>{const x=a.toLowerCase().trim(),y=b.toLowerCase().trim();return !!x&&!!y&&(x.includes(y)||y.includes(x));};
 const candidates=discoveryId&&data.mode==='synced'?data.jobs.filter(j=>/^JOB-\d{3,8}$/.test(j.id)).slice().sort((a,b)=>Number(same(b.employer,item.employer))-Number(same(a.employer,item.employer))||a.employer.localeCompare(b.employer)||a.role.localeCompare(b.role)):[];
 async function link(body:object,done:string){if(locked||inFlight.current)return;inFlight.current=true;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/scout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(45000)}),v=await r.json() as {saved?:boolean;message?:string;error?:string};if(!r.ok||!v.saved)throw new Error(v.error||'The link was not saved.');setNotice(v.message||done);setSure(false);setTarget('');await refresh();}catch(e){setError(e instanceof Error?e.message:'The link was not saved.');}finally{inFlight.current=false;setBusy(false);}}
 async function recordApplied(){if((!item.review&&!item.discovery)||inFlight.current||(!application.current&&(!canApply||!confirm)))return;if(locked)return;inFlight.current=true;setBusy(true);setError('');setNotice('');application.current??={requestId:'HQ-A-'+crypto.randomUUID(),appliedOn:date};
  try{const result=await recordDiscoveryApplication(item.review,application.current,fetch,item.discovery?.id||item.review?.job.id||'');setNotice(result.alreadyRecorded?'The tracker already records this application; no status overwrite was made.':result.recordId+' · Applied confirmed in '+recordsHome(data)+'.');application.current=null;setChoice(null);await refresh();await sync();}catch(e){setError(e instanceof Error?e.message:'confirmation unavailable. Retry this same request.');}finally{inFlight.current=false;setBusy(false);}}
 return <section className="job-decisions" aria-label="Your decision beside agent advice"><div className="job-decision-heading"><div><p className="eyebrow">YOUR DECISION</p><h3>{feedback?.decision==='not-fit'?'Not a fit for me':applied?'Application recorded':'What do you think?'}</h3></div><span>Separate from agent advice</span></div>
 {feedback&&<p className="job-owner-note">{feedback.decision==='not-fit'?feedback.reason:'Returned to review'} · {new Date(feedback.at).toLocaleString('en-GB',{timeZone:zone()})}<small>Saved privately in HQ · The application status in your tracker is preserved.</small></p>}
 <div className="job-decision-actions"><button className="subtle-button" disabled={!canApply} onClick={()=>{setChoice('applied');setConfirm(false);setError('');}}><Check size={16}/>{applied?'Applied':"I've applied"}</button>{feedback?.decision==='not-fit'?<button className="subtle-button" disabled={locked} onClick={()=>decide('review')}><RotateCcw size={15}/>Return to review</button>:<button className="subtle-button" disabled={locked} onClick={()=>{setChoice('not-fit');setError('');}}><X size={16}/>Not a fit</button>}</div>
 {!real&&<p className="quiet">Demo jobs cannot save decisions to your private data.</p>}{!item.job&&!canApply&&!applied&&real&&<p className="quiet">Recording an application needs a working database connection and no task running.</p>}
 {error&&<p className="connection-feedback error" role="alert">{error}</p>}{notice&&<p className="connection-feedback success" role="status">{notice}</p>}
 {choice==='not-fit'&&<form onSubmit={e=>{e.preventDefault();decide('not-fit');}}><label className="connection-field">Why isn't this a fit?<select value={reason} disabled={locked} onChange={e=>setReason(e.target.value)}>{['Role / responsibilities','Required experience','Location / commute','Language requirement','Salary / contract','Other'].map(r=><option key={r}>{r}</option>)}</select></label><label className="connection-field">Optional note<textarea maxLength={450} rows={2} value={note} disabled={locked} onChange={e=>setNote(e.target.value)}/></label><p className="quiet">Moves this vacancy out of recommendations. It does not change the agents' assessment or the outcome in your tracker.</p><div className="job-decision-actions"><button className="primary-button" disabled={locked}>{busy?'Saving…':'Save not a fit'}</button><button className="text-button" type="button" disabled={busy} onClick={()=>setChoice(null)}>Cancel</button></div></form>}
 {choice==='applied'&&(item.job?<ApplicationRecord job={item.job} data={data} scout={state} replay={replay} onRefresh={sync} initialOpen/>:<form onSubmit={e=>{e.preventDefault();recordApplied();}}><label className="connection-field">Application date<input type="date" required value={date} max={amsterdamToday()} disabled={locked||!!application.current} onChange={e=>{setDate(e.target.value);setConfirm(false);}}/></label><p className="quiet">First saves this discovery to the database, then records your Applied status and date. Existing evidence and later outcomes are preserved.</p>{overrides&&<p className="quiet">The screening did not recommend this vacancy, or has not reviewed it. That is advice: you decide. The job's history will say it was saved on your decision.</p>}<label className="application-check"><input type="checkbox" checked={confirm} disabled={locked||!!application.current} onChange={e=>setConfirm(e.target.checked)}/>I reviewed this vacancy and already submitted the application myself.</label><div className="job-decision-actions"><button className="primary-button" disabled={locked||(!application.current&&(!confirm||!date))}>{busy?'Saving…':application.current?'Retry the same request':'Save to the database & record applied'}</button><button className="text-button" type="button" disabled={busy||!!application.current} onClick={()=>setChoice(null)}>Cancel</button></div></form>)}
 {candidates.length>0&&<details className="job-link"><summary><Link2 size={15}/> Already one of your jobs? Link it</summary><p className="quiet">For a vacancy you already have that was posted somewhere else too. This posting then shows inside that job, not as a new one. The job, its status and its history are not changed, and you can undo the link.</p><label className="connection-field">The job it belongs to<select value={target} disabled={locked} onChange={e=>{setTarget(e.target.value);setSure(false);}}><option value="">Choose a job…</option>{candidates.map(j=><option key={j.id} value={j.id}>{j.employer} · {j.role} · {j.status}</option>)}</select></label><div className="job-decision-actions"><button type="button" className={sure?'primary-button':'subtle-button'} disabled={locked||!target} onClick={()=>sure?link({action:'link-job',jobId:discoveryId,recordId:target},'Linked.'):setSure(true)}>{busy?'Saving…':sure?'Confirm: same job as '+target:'Link to this job'}</button>{sure&&!busy&&<button type="button" className="text-button" onClick={()=>setSure(false)}>Cancel</button>}</div></details>}
 {item.job&&!!item.linked?.length&&<div className="job-link"><p className="eyebrow">ALSO POSTED AS</p>{item.linked.map(l=><p key={l.jobId} className="job-owner-note">{l.title} · {l.employer}{l.source?' · '+l.source:''}<small>Linked by you on {new Date(l.at).toLocaleDateString('en-GB',{timeZone:zone()})} · <button type="button" className="text-button" disabled={locked} onClick={()=>link({action:'unlink-job',jobId:l.jobId},'Link removed.')}>Unlink</button></small></p>)}</div>}
 {feedback&&feedback.history.length>0&&<details><summary>Recent owner decisions</summary>{feedback.history.map(h=><p key={h.id}>{h.decision==='not-fit'?'Not a fit':'Returned to review'} · {h.reason} · {new Date(h.at).toLocaleString('en-GB',{timeZone:zone()})}</p>)}</details>}
 </section>;
}
