import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {Check,ExternalLink,Mail,RefreshCw,ShieldCheck} from 'lucide-react';
import type {Job,Snapshot} from './data';
import {hasApplication,type ApplicationReceipt} from './application-record';
import './mail.css';
import {zone} from './zone';
type MailCandidate={key:string;subject:string;sender:string;receivedAt:string;url:string;excerpt:string;kind:string;match:string;reference:string;attached:ApplicationReceipt|null};
type MailCheck={recordId:string;checkedAt:string;from:string;to:string;scanned:number;capped:boolean;candidates:MailCandidate[]};
type MailState={protected:boolean;configured:boolean;browserReady:boolean;clientSecretConfigured:boolean;redirectUri:string;signInError:string|null;connected:boolean;clientId:string;verifiedAt:string|null;lastCheck:string|null;error:string|null;checks:MailCheck[]};
type MailResponse={error?:string;message?:string;status?:string;userCode?:string;url?:string;expiresAt?:string;interval?:number;saved?:boolean;checked?:boolean;result?:MailCheck;receipt?:ApplicationReceipt};
const blank:MailState={protected:false,configured:false,browserReady:false,clientSecretConfigured:false,redirectUri:'',signInError:null,connected:false,clientId:'',verifiedAt:null,lastCheck:null,error:null,checks:[]};
const time=(s:string)=>new Date(s).toLocaleString('en-GB',{timeZone:zone()});
function useMail(){const [state,setState]=useState(blank),[error,setError]=useState(''),[busy,setBusy]=useState(false),inflight=useRef(false);
  const load=useCallback(async()=>{try{const r=await fetch('/api/mail',{cache:'no-store',signal:AbortSignal.timeout(15000)}),v=await r.json() as MailState;if(!r.ok)throw Error(v.error||'Mail connection unavailable.');setState({...blank,...v});}catch(e){setError(e instanceof Error?e.message:'Mail connection unavailable.');}},[]);
  useEffect(()=>{load();},[load]);
  const action=async(body:object)=>{if(inflight.current)throw Error('An email action is already running.');inflight.current=true;setBusy(true);setError('');try{const r=await fetch('/api/mail',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(120000)}),v=await r.json() as MailResponse;if(!r.ok)throw Error(v.error||'Email check unavailable.');await load();return v;}catch(e){setError(e instanceof Error?e.message:'Email check unavailable; saved evidence retained.');throw e;}finally{inflight.current=false;setBusy(false);}};
  return {state,error,busy,action};
}
export function OutlookConnection(){
  const {state,error,busy,action}=useMail(),[clientId,setClientId]=useState(''),[clientSecret,setClientSecret]=useState(''),[notice,setNotice]=useState('');
  useEffect(()=>setClientId(state.clientId),[state.clientId]);
  useEffect(()=>{const u=new URL(window.location.href);if(u.searchParams.has('outlook')){u.searchParams.delete('outlook');window.history.replaceState(window.history.state,'',u.pathname+u.search+u.hash);}},[]);
  async function run(body:object){try{const result=await action(body);setNotice(result.message||'');return result;}catch{return null;}}
  const save=(e:FormEvent)=>{e.preventDefault();const secret=clientSecret.trim();setClientSecret('');run({action:'save',clientId:clientId.trim(),...(secret?{clientSecret:secret}:{})});};
  async function connect(){const result=await run({action:'connect-browser'});if(result?.status==='redirect'&&result.url){const u=new URL(result.url);if(u.origin==='https://login.microsoftonline.com'&&u.pathname==='/common/oauth2/v2.0/authorize')window.location.assign(u.href);else setNotice('Microsoft sign-in address could not be verified.');}}
  return <article className="outlook-connection source-card"><header><Mail size={23}/><div><p className="eyebrow">PRIVATE EMAIL / READ ONLY</p><h3>Outlook evidence</h3></div></header><p>{state.connected?'Microsoft mail reading verified. Check a tracked vacancy for matching emails, then attach the evidence you reviewed.':'Connect Outlook or Hotmail directly to HQ. Your chat connector does not connect this hosted app.'}</p>
    <p className="quiet">Mail.Read + offline access. No send, delete, application submission or outcome changes. Tokens are encrypted on this server.</p>{state.verifiedAt&&<small>Connection verified: {time(state.verifiedAt)}</small>}
    {(error||state.error||state.signInError)&&<p className="connection-feedback error" role="alert">{error||state.error||state.signInError}</p>}{notice&&<p className="connection-feedback success" role="status">{notice}</p>}
    <details open={!state.browserReady}><summary>Set up your Microsoft app</summary><ol><li>Use your <b>Job Hunt</b> app registration in Microsoft Entra, supporting personal Microsoft accounts.</li><li>Authentication → Add Redirect URI → <b>Web</b>: register the exact return address shown below. Keep implicit token flows off.</li><li>API permissions → Microsoft Graph → Delegated permissions: <b>Mail.Read</b>. HQ requests offline access so it can refresh the connection privately.</li><li>Certificates &amp; secrets → New client secret. Copy its <b>Value</b> directly into the private field below. Keep the secret out of chat and GitHub.</li><li>Save the app settings, then choose <b>Connect Outlook</b>. Sign in yourself on Microsoft and review the read-only consent. Microsoft returns you to HQ, which verifies mailbox reading.</li></ol>{state.redirectUri&&<label className="connection-field">Web return address<input readOnly value={state.redirectUri} aria-label="Microsoft Web return address"/></label>}<p>If registration is unavailable, you can still record your application and add an owner-provided email reference.</p><a className="text-button" href="https://entra.microsoft.com/" target="_blank" rel="noreferrer">Microsoft Entra <ExternalLink size={14}/></a> <a className="text-button" href="https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-auth-code-flow" target="_blank" rel="noreferrer">Microsoft connection guide <ExternalLink size={14}/></a></details>
    <form onSubmit={save}><label className="connection-field">Application (client) ID<input value={clientId} onChange={e=>setClientId(e.target.value)} required placeholder="00000000-0000-0000-0000-000000000000" disabled={busy||!state.protected}/></label><label className="connection-field">Client secret Value<input type="password" autoComplete="off" value={clientSecret} onChange={e=>setClientSecret(e.target.value)} minLength={12} maxLength={1024} placeholder={state.clientSecretConfigured?'Saved privately · leave blank to keep it':'Paste the Value from Microsoft here'} disabled={busy||!state.protected}/></label>{state.clientSecretConfigured&&<small>App credential saved privately. The saved value is never displayed.</small>}<button className="subtle-button" disabled={busy||!state.protected}>Save private Microsoft settings</button></form>
    {!state.browserReady&&<p className="quiet">Browser sign-in needs the Web return address and private app credential above.</p>}
    <div className="mail-actions"><button className="primary-button" disabled={busy||!state.browserReady||!state.protected} onClick={connect}><Mail size={16}/>{busy?'Connecting…':state.connected?'Reconnect Outlook':'Connect Outlook'}</button>{state.connected&&<button className="subtle-button" disabled={busy} onClick={()=>run({action:'disconnect'})}>Disconnect HQ mail access</button>}</div>
  </article>;
}
export function MailEvidence({job,data,replay,onConnect,onRefresh}:{job:Job;data:Snapshot;replay:boolean;onConnect:()=>void;onRefresh:()=>Promise<Snapshot|undefined>}){
  const {state,error,busy,action}=useMail(),[notice,setNotice]=useState(''),[confirmed,setConfirmed]=useState('');
  const result=state.checks.find(r=>r.recordId===job.id),locked=busy||data.mode!=='synced'||data.stale||replay||!state.connected||!hasApplication(job);
  async function check(){setNotice('');setConfirmed('');try{const r=await action({action:'check',recordId:job.id});setNotice(r.message||'Email check completed.');}catch{}}
  async function attach(key:string){try{const r=await action({action:'attach',recordId:job.id,key,confirmEvidence:true});setNotice(r.message||'Evidence saved.');setConfirmed('');await onRefresh();}catch{}}
  return <section className="mail-evidence" aria-label="Outlook evidence"><header><Mail size={18}/><h3>Check your Outlook evidence</h3></header><p>Look for emails matching this tracked employer and role. Review the message before adding its reference to the database. No status or outcome is inferred from an email.</p>
    {!state.connected?<><p className="quiet">Hosted Outlook access is not connected. Your saved email references remain available.</p><button className="subtle-button" onClick={onConnect}>Set up Outlook in Connections</button></>:<button className="subtle-button" disabled={locked} onClick={check}><RefreshCw size={15}/>{busy?'Checking private email…':'Check Outlook for this vacancy'}</button>}
    {!hasApplication(job)&&<p className="quiet">Record your application first.</p>}{(data.stale||replay)&&<p className="quiet">Refresh the tracker and leave historical replay before checking email.</p>}
    {error&&<p className="connection-feedback error" role="alert">{error} Last successful evidence remains below.</p>}{notice&&<p className="connection-feedback success" role="status">{notice}</p>}
    {result&&<><p className="quiet">Checked {time(result.checkedAt)} · {result.scanned} messages in the bounded window {time(result.from)} – {time(result.to)}.{result.capped?' Scan limit reached; this is a partial check.':' This is a bounded check, not a full mailbox audit.'}</p>{!result.candidates.length&&<p>No exact employer and role / posting ID matches found in that window. This does not establish that no email exists.</p>}
      {result.candidates.map(c=><article className="mail-match" key={c.key}><span className="eyebrow">{c.kind==='outlook-receipt'?'POSSIBLE APPLICATION RECEIPT':'MATCHING EMAIL / NO OUTCOME INFERRED'}</span><h4>{c.subject}</h4><small>{c.sender} · {time(c.receivedAt)}</small><p>{c.excerpt}</p><p className="quiet">{c.match} A sender address is not proof of authenticity.</p>{c.url&&<a className="text-button" href={c.url} target="_blank" rel="noreferrer">Review in Outlook <ExternalLink size={14}/></a>}{c.attached?<p className="mail-attached"><Check size={15}/>Evidence saved · {c.attached.recordId} / {c.attached.eventId}</p>:<><label className="application-check"><input type="checkbox" checked={confirmed===c.key} disabled={locked} onChange={e=>setConfirmed(e.target.checked?c.key:'')}/>I reviewed this message and it relates to this vacancy.</label><button className="subtle-button" disabled={locked||confirmed!==c.key} onClick={()=>attach(c.key)}>Add this email evidence to the database</button></>}</article>)}
    </>}
    <p className="quiet"><ShieldCheck size={14}/>Saved message references stay private. Existing tracker evidence is appended to, never replaced.</p>
  </section>;
}
