import {useEffect,useRef,useState} from 'react';
import {Check,Download,FileText,Plus,Sparkles,Trash2,Upload} from 'lucide-react';
import './profile.css';
import {renderCv,templates,accents,type TemplateId} from './cv-templates';
import type {ScoutState} from './scout';
import {zone} from './zone';
type Variant={jobId:string;employer:string;title:string;profile:Profile;changes:string[];dropped:string[];note:string};

export type Experience={title:string;employer:string;location:string;start:string;end:string;points:string[]};
export type Education={degree:string;school:string;start:string;end:string;notes:string};
export type Profile={name:string;headline:string;email:string;phone:string;location:string;links:string[];about:string;skills:string[];languages:{name:string;level:string}[];experience:Experience[];education:Education[];certificates:string[]};
type CvFile={filename:string;size:number;uploadedAt:string;characters:number};
type Photo={type:string;size:number;uploadedAt:string};
type State={protected?:boolean;ready:boolean;profile:Profile;savedAt?:string|null;cv:CvFile|null;photo?:Photo|null;message?:string};
const stamp=(at:string)=>new Date(at).toLocaleString('en-GB',{timeZone:zone(),day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});
const lines=(value:string)=>value.split('\n').map(v=>v.trim()).filter(Boolean);
// My CV: the uploaded file and the fields the owner keeps up to date. Everything shown here is what the owner saved; nothing is filled in or sent anywhere by itself.
const PASTE='__paste__';
export default function ProfilePage({onSettings,scout,request}:{onSettings:()=>void;scout:ScoutState;request?:{jobId?:string;title:string;employer:string;location:string;nonce:number}|null}){
  const [state,setState]=useState<State|null>(null),[profile,setProfile]=useState<Profile|null>(null),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[skill,setSkill]=useState(''),[sure,setSure]=useState(false),[variant,setVariant]=useState<Variant|null>(null),[vacancy,setVacancy]=useState(''),[sureCv,setSureCv]=useState(false),[pasted,setPasted]=useState({title:'',employer:'',location:'',description:''}),adaptCard=useRef<HTMLElement>(null),[proposed,setProposed]=useState(''),file=useRef<HTMLInputElement>(null),picture=useRef<HTMLInputElement>(null),sheet=useRef<HTMLIFrameElement>(null),[template,setTemplate]=useState<TemplateId>('classic'),[accent,setAccent]=useState(accents[0]),[withPhoto,setWithPhoto]=useState(true),[photoData,setPhotoData]=useState('');
  // The stored photo is read once into the page so the CV preview can embed it; it is not sent anywhere from here.
  const photoAt=state?.photo?.uploadedAt||'';
  useEffect(()=>{if(!photoAt){setPhotoData('');return;}let stopped=false;fetch('/api/profile?file=photo',{cache:'no-store',signal:AbortSignal.timeout(20000)}).then(r=>r.ok?r.blob():null).then(blob=>{if(!blob||stopped)return;const reader=new FileReader();reader.onload=()=>{if(!stopped)setPhotoData(String(reader.result||''));};reader.readAsDataURL(blob);}).catch(()=>{});return()=>{stopped=true;};},[photoAt]);
  useEffect(()=>{let stopped=false;fetch('/api/profile',{cache:'no-store',signal:AbortSignal.timeout(20000)}).then(async r=>{const v=await r.json() as State&{error?:string};if(stopped)return;if(!r.ok)throw new Error(v.error||'Your CV could not be loaded.');setState(v);setProfile(v.profile);}).catch(e=>{if(!stopped)setError(e instanceof Error?e.message:'Your CV could not be loaded.');});return()=>{stopped=true;};},[]);
  const change=(patch:Partial<Profile>)=>{setProfile(p=>p?{...p,...patch}:p);setDirty(true);setNotice('');};
  async function save(){if(!profile||busy)return;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save',profile}),signal:AbortSignal.timeout(30000)}),v=await r.json() as {saved?:boolean;profile?:Profile;savedAt?:string;message?:string;error?:string};if(!r.ok||!v.saved||!v.profile)throw new Error(v.error||'Not saved.');setProfile(v.profile);setState(s=>s?{...s,profile:v.profile!,savedAt:v.savedAt}:s);setDirty(false);setProposed('');setNotice(v.message||'Saved.');}catch(e){setError(e instanceof Error?e.message:'Not saved.');}finally{setBusy(false);}}
  async function upload(chosen:File|undefined){if(!chosen||busy)return;if(chosen.type!=='application/pdf'&&!/\.pdf$/i.test(chosen.name)){setError('Choose a PDF file.');return;}if(chosen.size>5_000_000){setError('Choose a PDF of at most 5 MB.');return;}setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/pdf','X-File-Name':encodeURIComponent(chosen.name)},body:chosen,signal:AbortSignal.timeout(60000)}),v=await r.json() as {saved?:boolean;cv?:CvFile;message?:string;error?:string};if(!r.ok||!v.saved||!v.cv)throw new Error(v.error||'The CV was not stored.');setState(s=>s?{...s,cv:v.cv!}:s);setNotice(v.message||'Stored.');}catch(e){setError(e instanceof Error?e.message:'The CV was not stored.');}finally{setBusy(false);if(file.current)file.current.value='';}}
  // Asks the model to copy the stored CV into the fields. The answer replaces what is on screen but is not saved: the owner checks it and saves.
  async function fill(){if(busy)return;if(!sure){setSure(true);return;}setSure(false);setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/scout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'ai-profile',confirm:true}),signal:AbortSignal.timeout(240000)}),v=await r.json() as {proposed?:boolean;profile?:Profile;model?:string;cost?:number|null;message?:string;error?:string};if(!r.ok||!v.proposed||!v.profile)throw new Error(v.error||'The fields were not filled.');setProfile(v.profile);setDirty(true);setProposed('Filled in by '+(v.model||'the model')+' from your uploaded CV'+(typeof v.cost==='number'?' · about $'+v.cost.toFixed(2):'')+' · not saved yet');setNotice(v.message||'Filled in. Check and save.');}catch(e){setError(e instanceof Error?e.message:'The fields were not filled.');}finally{setBusy(false);}}
  // Vacancies HQ holds with enough text to adapt a CV to: current discoveries, and reviewed ones that have left their source.
  const vacancies=(()=>{const seen=new Set<string>(),out:{id:string;label:string}[]=[];for(const job of [...(scout.results||[]),...(scout.workflows||[]).filter(w=>!w.superseded).map(w=>w.job)]){if(!job?.id||seen.has(job.id)||String(job.description||'').length<200)continue;seen.add(job.id);out.push({id:job.id,label:job.employer+' · '+job.title});}return out.sort((a,b)=>a.label.localeCompare(b.label));})();
  // Asks the model for a CV adapted to one vacancy. The answer is shown below instead of the full CV; it is not saved, and the saved details stay as they are.
  // Arriving from a job page: that vacancy is chosen, or, when HQ has no text for it, the paste form opens with its title and employer filled in.
  const ready=!!state?.ready;
  useEffect(()=>{if(!request||!ready)return;if(request.jobId&&vacancies.some(v=>v.id===request.jobId))setVacancy(request.jobId);else{setVacancy(PASTE);setPasted({title:request.title,employer:request.employer,location:request.location,description:''});}setVariant(null);setSureCv(false);setTimeout(()=>adaptCard.current?.scrollIntoView({behavior:'smooth',block:'center'}),150);},[request?.nonce,ready]);
  const pasteReady=pasted.title.trim().length>0&&pasted.employer.trim().length>0&&pasted.description.trim().length>=200;
  async function adapt(){if(busy||!vacancy||(vacancy===PASTE&&!pasteReady))return;if(dirty){setError('Save your details first, so the adapted CV is built from what you see.');return;}if(!sureCv){setSureCv(true);return;}setSureCv(false);setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/scout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(vacancy===PASTE?{action:'ai-cv',confirm:true,vacancy:pasted}:{action:'ai-cv',confirm:true,jobId:vacancy}),signal:AbortSignal.timeout(240000)}),v=await r.json() as {proposed?:boolean;jobId?:string;employer?:string;title?:string;variant?:Profile;changes?:string[];dropped?:string[];model?:string;cost?:number|null;message?:string;error?:string};if(!r.ok||!v.proposed||!v.variant)throw new Error(v.error||'The CV was not prepared.');setVariant({jobId:v.jobId||'',employer:v.employer||'',title:v.title||'',profile:v.variant,changes:v.changes||[],dropped:v.dropped||[],note:'Prepared by '+(v.model||'the model')+(typeof v.cost==='number'?' · about $'+v.cost.toFixed(2):'')});setNotice(v.message||'Prepared. Check it before you download.');}catch(e){setError(e instanceof Error?e.message:'The CV was not prepared.');}finally{setBusy(false);}}
  const shown=variant?.profile||profile,tune=(patch:Partial<Profile>)=>setVariant(v=>v?{...v,profile:{...v.profile,...patch}}:v);
  async function uploadPhoto(chosen:File|undefined){if(!chosen||busy)return;if(!['image/jpeg','image/png'].includes(chosen.type)){setError('Choose a JPG or PNG picture.');return;}if(chosen.size>2_000_000){setError('Choose a photo of at most 2 MB.');return;}setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/profile',{method:'POST',headers:{'Content-Type':chosen.type},body:chosen,signal:AbortSignal.timeout(60000)}),v=await r.json() as {saved?:boolean;photo?:Photo;message?:string;error?:string};if(!r.ok||!v.saved||!v.photo)throw new Error(v.error||'The photo was not stored.');setState(s=>s?{...s,photo:v.photo!}:s);setNotice(v.message||'Stored.');}catch(e){setError(e instanceof Error?e.message:'The photo was not stored.');}finally{setBusy(false);if(picture.current)picture.current.value='';}}
  async function removePhoto(){if(busy)return;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'remove-photo'}),signal:AbortSignal.timeout(30000)}),v=await r.json() as {saved?:boolean;message?:string;error?:string};if(!r.ok||!v.saved)throw new Error(v.error||'The photo was not removed.');setState(s=>s?{...s,photo:null}:s);setNotice(v.message||'Removed.');}catch(e){setError(e instanceof Error?e.message:'The photo was not removed.');}finally{setBusy(false);}}
  // The browser prints the CV page to a file; "Save as PDF" is the destination to choose in its dialog.
  const print=()=>{const page=sheet.current?.contentWindow;if(page){page.focus();page.print();}};
  if(error&&!state)return <section className="scout-view"><div className="connection-feedback error" role="alert">{error}</div></section>;
  if(!state||!profile)return <section className="scout-view"><p className="quiet">Loading your CV…</p></section>;
  if(!state.protected)return null;
  if(!state.ready)return <section className="scout-view"><article className="source-card"><header><FileText size={23}/><div><p className="eyebrow">MY CV</p><h3>Your database comes first</h3></div></header><p>{state.message||'Your CV is kept in your own database.'}</p><div className="scout-actions source-actions"><button className="subtle-button" onClick={onSettings}>Open Settings</button></div></article></section>;
  const field=(label:string,value:string,set:(v:string)=>void,more:{type?:string;max?:number;placeholder?:string}={})=><label className="connection-field">{label}<input type={more.type||'text'} value={value} maxLength={more.max||160} placeholder={more.placeholder} disabled={busy} onChange={e=>set(e.target.value)}/></label>;
  const setExperience=(i:number,patch:Partial<Experience>)=>change({experience:profile.experience.map((x,n)=>n===i?{...x,...patch}:x)}),setEducation=(i:number,patch:Partial<Education>)=>change({education:profile.education.map((x,n)=>n===i?{...x,...patch}:x)});
  const addSkill=()=>{const value=skill.trim().slice(0,80);if(value&&!profile.skills.some(s=>s.toLowerCase()===value.toLowerCase()))change({skills:[...profile.skills,value]});setSkill('');};
  return <section className="scout-view profile-page">
    {error&&<div className="connection-feedback error" role="alert">{error}</div>}{notice&&<div className="connection-feedback success" role="status"><Check size={17}/>{notice}</div>}
    <article className="source-card"><header><Upload size={23}/><div><p className="eyebrow">YOUR CV FILE</p><h3>{state.cv?state.cv.filename:'No CV uploaded yet'}</h3></div><span className="badge">{state.cv?'Stored':'Missing'}</span></header>
      <p>{state.cv?`Uploaded ${stamp(state.cv.uploadedAt)} · ${Math.round(state.cv.size/1024)} KB · ${state.cv.characters} characters of text read from it.`:'Upload your current CV as a PDF. It is stored in your own database, together with the text read from it.'} Uploading a new file replaces the stored one. The fields below are not changed by an upload.</p>
      <div className="scout-actions source-actions"><input ref={file} type="file" accept="application/pdf,.pdf" hidden onChange={e=>upload(e.target.files?.[0])}/><button className="subtle-button" disabled={busy} onClick={()=>file.current?.click()}><Upload size={15}/>{busy?'Working…':state.cv?'Replace the PDF':'Upload a PDF'}</button>{state.cv&&<a className="text-button" href="/api/profile?file=cv"><Download size={14}/>Download the stored file</a>}</div>
      {state.cv&&state.cv.characters>=200&&<div className="profile-block"><strong>Fill the fields from this CV</strong><p className="quiet">One paid request to the AI model. Your whole CV text, including your name and contact details, is sent to Anthropic for it. The answer fills the fields below in place of what is there now, but nothing is saved until you have checked it and pressed Save.</p><div className="scout-actions source-actions"><button className="subtle-button" disabled={busy} onClick={fill}><Sparkles size={15}/>{busy?'Reading your CV…':sure?'Confirm: send my CV text and fill the fields':'Fill the fields from my CV'}</button>{sure&&!busy&&<button className="text-button" onClick={()=>setSure(false)}>Cancel</button>}</div></div>}</article>
    <article className="source-card"><header><FileText size={23}/><div><p className="eyebrow">YOUR DETAILS</p><h3>What goes on your CV</h3></div><span className="badge">{dirty&&proposed?'Proposal · not saved':dirty?'Unsaved changes':state.savedAt?'Saved '+stamp(state.savedAt):'Not filled in yet'}</span></header>
      <p>These fields are yours to keep up to date. Add a skill, rewrite the About me, or correct a date whenever something changes.</p>{dirty&&proposed&&<div className="connection-feedback" role="status">{proposed}. The model can misread a PDF: check names, dates and every point before you save.</div>}
      <div className="scout-search-fields">{field('Full name',profile.name,v=>change({name:v}),{max:120})}{field('Headline',profile.headline,v=>change({headline:v}),{placeholder:'For example: Digital Analyst · CRO'})}</div>
      <div className="scout-search-fields">{field('Email',profile.email,v=>change({email:v}),{type:'email'})}{field('Phone',profile.phone,v=>change({phone:v}),{max:60})}</div>
      <div className="scout-search-fields">{field('Location',profile.location,v=>change({location:v}),{max:120})}<label className="connection-field">Links, one per line<textarea rows={2} value={profile.links.join('\n')} disabled={busy} onChange={e=>change({links:lines(e.target.value).slice(0,6)})} placeholder="LinkedIn, portfolio"/></label></div>
      <label className="connection-field">About me<textarea rows={5} maxLength={2500} value={profile.about} disabled={busy} onChange={e=>change({about:e.target.value})}/></label>
      <div className="profile-block"><strong>Skills</strong><div className="profile-chips">{profile.skills.map(s=><span key={s}>{s}<button aria-label={'Remove skill '+s} disabled={busy} onClick={()=>change({skills:profile.skills.filter(x=>x!==s)})}>×</button></span>)}{!profile.skills.length&&<small className="quiet">No skills yet.</small>}</div><div className="profile-add"><input value={skill} maxLength={80} placeholder="Add a skill" aria-label="New skill" disabled={busy} onChange={e=>setSkill(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addSkill();}}}/><button className="subtle-button" disabled={busy||!skill.trim()} onClick={addSkill}><Plus size={15}/>Add</button></div></div>
      <div className="profile-block"><strong>Languages</strong>{profile.languages.map((l,i)=><div key={i} className="profile-row">{field('Language',l.name,v=>change({languages:profile.languages.map((x,n)=>n===i?{...x,name:v}:x)}),{max:60})}{field('Level',l.level,v=>change({languages:profile.languages.map((x,n)=>n===i?{...x,level:v}:x)}),{max:60,placeholder:'Native, fluent, B2…'})}<button className="icon-button" aria-label={'Remove language '+(l.name||i+1)} disabled={busy} onClick={()=>change({languages:profile.languages.filter((_,n)=>n!==i)})}><Trash2 size={15}/></button></div>)}<button className="text-button" disabled={busy||profile.languages.length>=12} onClick={()=>change({languages:[...profile.languages,{name:'',level:''}]})}><Plus size={14}/>Add a language</button></div>
      <div className="profile-block"><strong>Experience</strong>{profile.experience.map((x,i)=><div key={i} className="profile-entry"><div className="scout-search-fields">{field('Job title',x.title,v=>setExperience(i,{title:v}))}{field('Employer',x.employer,v=>setExperience(i,{employer:v}))}</div><div className="profile-row">{field('Location',x.location,v=>setExperience(i,{location:v}),{max:120})}{field('From',x.start,v=>setExperience(i,{start:v}),{max:20,placeholder:'2022-03'})}{field('Until',x.end,v=>setExperience(i,{end:v}),{max:20,placeholder:'Present'})}</div><label className="connection-field">What you did, one point per line<textarea rows={4} value={x.points.join('\n')} disabled={busy} onChange={e=>setExperience(i,{points:e.target.value.split('\n').slice(0,12)})} onBlur={e=>setExperience(i,{points:lines(e.target.value).slice(0,12)})}/></label><button className="text-button" disabled={busy} onClick={()=>change({experience:profile.experience.filter((_,n)=>n!==i)})}><Trash2 size={14}/>Remove this job</button></div>)}<button className="text-button" disabled={busy||profile.experience.length>=25} onClick={()=>change({experience:[...profile.experience,{title:'',employer:'',location:'',start:'',end:'',points:[]}]})}><Plus size={14}/>Add a job</button></div>
      <div className="profile-block"><strong>Education</strong>{profile.education.map((x,i)=><div key={i} className="profile-entry"><div className="scout-search-fields">{field('Degree or course',x.degree,v=>setEducation(i,{degree:v}),{max:200})}{field('School',x.school,v=>setEducation(i,{school:v}),{max:200})}</div><div className="profile-row">{field('From',x.start,v=>setEducation(i,{start:v}),{max:20})}{field('Until',x.end,v=>setEducation(i,{end:v}),{max:20})}</div><label className="connection-field">Notes<textarea rows={2} maxLength={600} value={x.notes} disabled={busy} onChange={e=>setEducation(i,{notes:e.target.value})}/></label><button className="text-button" disabled={busy} onClick={()=>change({education:profile.education.filter((_,n)=>n!==i)})}><Trash2 size={14}/>Remove</button></div>)}<button className="text-button" disabled={busy||profile.education.length>=12} onClick={()=>change({education:[...profile.education,{degree:'',school:'',start:'',end:'',notes:''}]})}><Plus size={14}/>Add education</button></div>
      <label className="connection-field">Certificates and courses, one per line<textarea rows={3} value={profile.certificates.join('\n')} disabled={busy} onChange={e=>change({certificates:e.target.value.split('\n').slice(0,25)})} onBlur={e=>change({certificates:lines(e.target.value).slice(0,25)})}/></label>
      <div className="scout-actions source-actions profile-save"><button className="primary-button" disabled={busy||!dirty} onClick={save}><Check size={16}/>{busy?'Saving…':'Save my details'}</button>{dirty&&<small className="quiet">You have unsaved changes.</small>}</div></article>
    <article className="source-card" ref={adaptCard}><header><Sparkles size={23}/><div><p className="eyebrow">FOR ONE VACANCY</p><h3>Adapt my CV to a vacancy</h3></div><span className="badge">{vacancies.length} vacancies</span></header>
      <p>The model picks the skills and experience points from your saved details that matter most for one vacancy, puts them in order, and writes a headline and profile text for it. It cannot add anything that is not in your details: whatever it returns is checked against them. One paid request; your saved details, including your name and contact data, and the vacancy text are sent to Anthropic for it.</p>
      <div className="cv-adapt"><label className="connection-field">Vacancy<select value={vacancy} disabled={busy} onChange={e=>{setVacancy(e.target.value);setSureCv(false);}}><option value="">Choose a vacancy…</option><option value={PASTE}>Another vacancy: I paste its text</option>{vacancies.map(v=><option key={v.id} value={v.id}>{v.label}</option>)}</select></label>{vacancy===PASTE&&<div className="cv-paste"><div className="scout-search-fields"><label className="connection-field">Job title<input value={pasted.title} maxLength={200} disabled={busy} onChange={e=>setPasted({...pasted,title:e.target.value})}/></label><label className="connection-field">Employer<input value={pasted.employer} maxLength={200} disabled={busy} onChange={e=>setPasted({...pasted,employer:e.target.value})}/></label></div><label className="connection-field">Vacancy text<textarea rows={7} maxLength={20000} value={pasted.description} disabled={busy} placeholder="Paste the full text of the vacancy here" onChange={e=>setPasted({...pasted,description:e.target.value})}/></label><small className="quiet">{pasted.description.trim().length<200?'Paste at least a few sentences of the vacancy.':'The pasted text is used for this request only and is not saved.'}</small></div>}<div className="scout-actions source-actions"><button className="subtle-button" disabled={busy||!vacancy||(vacancy===PASTE&&!pasteReady)} onClick={adapt}><Sparkles size={15}/>{busy?'Preparing…':sureCv?'Confirm: send my details and prepare this CV':'Prepare a CV for this vacancy'}</button>{sureCv&&!busy&&<button className="text-button" onClick={()=>setSureCv(false)}>Cancel</button>}</div></div></article>
    {(()=>{const chosen=templates.find(t=>t.id===template)!,showPhoto=chosen.photo&&withPhoto&&!!photoData;return <article className="source-card"><header><FileText size={23}/><div><p className="eyebrow">YOUR CV AS A PDF</p><h3>{variant?'CV for '+variant.employer:'Choose a template'}</h3></div><span className="badge">{variant?'Adapted · not saved':chosen.name}</span></header>
      {variant&&<div className="cv-variant"><div className="connection-feedback" role="status"><strong>Adapted to {variant.employer} · {variant.title}.</strong> {variant.note}. It selects and orders what is in your details; the headline and the profile text were written by the model. It is not saved: download it now, or go back to your full CV.</div>{variant.changes.length>0&&<ul className="cv-changes">{variant.changes.map((c,i)=><li key={i}>{c}</li>)}</ul>}{variant.dropped.length>0&&<p className="quiet">Left out because it is not in your details: {variant.dropped.join('; ')}.</p>}<label className="connection-field">Headline on this CV<input value={variant.profile.headline} maxLength={160} onChange={e=>tune({headline:e.target.value})}/></label><label className="connection-field">Profile text on this CV<textarea rows={4} maxLength={2500} value={variant.profile.about} onChange={e=>tune({about:e.target.value})}/></label><div className="profile-chips">{variant.profile.skills.map(s=><span key={s}>{s}<button aria-label={'Leave '+s+' off this CV'} onClick={()=>tune({skills:variant.profile.skills.filter(x=>x!==s)})}>×</button></span>)}</div><div className="scout-actions source-actions"><button className="text-button" onClick={()=>setVariant(null)}>Back to my full CV</button></div></div>}
      <p>The CV below is built here in your browser from {variant?'the adapted details shown here':'the details above, including changes you have not saved yet'}. Building and downloading it sends nothing anywhere. <strong>Download PDF</strong> opens your browser's print window: choose <em>Save as PDF</em> as the destination, and switch off "Headers and footers" if your browser adds them.</p>
      <div className="cv-templates" role="group" aria-label="CV template">{templates.map(t=><button key={t.id} className={t.id===template?'active':''} aria-pressed={t.id===template} onClick={()=>setTemplate(t.id)}><strong>{t.name}</strong><small>{t.about}</small></button>)}</div>
      <div className="cv-options"><div className="cv-accents" role="group" aria-label="Accent colour">{accents.map(c=><button key={c} aria-label={'Accent colour '+c} aria-pressed={c===accent} className={c===accent?'active':''} style={{background:c}} onClick={()=>setAccent(c)}/>)}</div>
        <div className="cv-photo"><input ref={picture} type="file" accept="image/jpeg,image/png" hidden onChange={e=>uploadPhoto(e.target.files?.[0])}/>{photoData&&<img src={photoData} alt="Your profile photo"/>}<button className="subtle-button" disabled={busy} onClick={()=>picture.current?.click()}><Upload size={15}/>{state.photo?'Replace photo':'Upload a photo'}</button>{state.photo&&<button className="text-button" disabled={busy} onClick={removePhoto}><Trash2 size={14}/>Remove</button>}{state.photo&&<label className="cv-check"><input type="checkbox" checked={withPhoto} disabled={!chosen.photo} onChange={e=>setWithPhoto(e.target.checked)}/> {chosen.photo?'Show my photo on this CV':'This template has no photo'}</label>}</div>
        <button className="primary-button" onClick={print}><Download size={16}/>Download PDF</button></div>
      <div className="cv-preview"><iframe ref={sheet} title="CV preview" sandbox="allow-same-origin allow-modals" srcDoc={shown?renderCv(shown,template,{accent,photo:showPhoto?photoData:''}):''}/></div></article>;})()}
    <p className="quiet">Screening reads your CV from the file stored here. An adapted CV is not saved: it exists until you leave this page or go back to your full CV.</p>
  </section>;
}
