import {Check,HelpCircle,FileText,ExternalLink} from 'lucide-react';
import {qualificationOverview,type QualificationProfile,type QualificationItem} from '../server/qualifications.mjs';
import {safeUrl} from './data';
import './qualifications.css';
import {zone} from './zone';
const stamp=(at:string)=>new Date(at).toLocaleString('en-GB',{timeZone:zone(),day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});
function Qualification({item}:{item:QualificationItem}){const yes=item.status==='documented';return <li className={yes?'qualification documented':'qualification'}><details><summary><span className="qualification-icon" aria-hidden="true">{yes?<Check size={18}/>:<HelpCircle size={18}/>}</span><strong>{item.label}</strong><span className="qualification-status">{yes?'CV mention':item.status==='check'?'Check with me':'Needs checking'}</span></summary><div className="qualification-evidence"><p><b>Vacancy excerpt</b>{item.vacancyEvidence}</p><p><b>CV evidence</b>{item.cvEvidence}</p><small>{item.note}</small></div></details></li>;}
export default function MatchOverview({description,profile,source,stale=false,demo=false}:{description:string;profile:QualificationProfile|null;source:string;stale?:boolean;demo?:boolean}){
 const result=qualificationOverview(description,demo?null:profile),link=safeUrl(result.cvSource||'');
 return <section className="qualification-overview" aria-label="Match overview"><header><FileText size={19}/><h3>Match overview</h3></header><p>How the recorded job details align with your linked CV.</p>{result.total?<><strong className="qualification-count">Qualifications: {result.hasProfile?result.documented+' of '+result.total+' documented':result.total+' to check'}</strong><p className="qualification-limit">Recognised mentions only, not a full fit score. Missing CV evidence needs checking.</p><ul className="qualification-list">{result.items.slice(0,5).map(item=><Qualification key={item.key} item={item}/>)}</ul>{result.total>5&&<details className="qualification-more"><summary>+{result.total-5} more qualifications</summary><ul className="qualification-list">{result.items.slice(5).map(item=><Qualification key={item.key} item={item}/>)}</ul></details>}</>:<p className="qualification-empty">No supported qualifications could be identified in the recorded text. Check the full vacancy; HQ will not invent a match count.</p>}{!result.hasProfile&&<p className="qualification-limit">{demo?'Demo record. Your private CV is not used here.':'CV comparison unavailable. Read your linked CV from Settings or start a review.'}</p>}<footer><span>{source}{stale?' · stale source':''}</span><span>{result.cvReadAt?'CV read '+stamp(result.cvReadAt):'CV reading not recorded'}</span>{link&&<a href={link} target="_blank" rel="noreferrer">View linked CV <ExternalLink size={12}/></a>}</footer></section>;
}
