import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {Search,Play,Pause,RefreshCw,ShieldCheck,FileText,ExternalLink,Info,Check,Radio} from 'lucide-react';
import type {ReviewWorkflow} from './workflow';
import {MatchEvidence,type MatchAssessment} from './match';
import {agentName} from './data';
import {ownerFeedbackFor,type OwnerFeedback} from './owner-feedback-model';
import type {OwnerStatus} from './owner-status-model';
import type {AiReview,AiRun,AiState,ModelRun,Motivation} from './analyst-ai';
import type {JSearchState} from './job-sources';
import {zone} from './zone';
export type ReviewState={runSummary?:null|{at:string;added:number;total:number;sources:number;failed:number};screenSkipped?:string|null;jsearch?:JSearchState;ai?:AiState;aiReviews?:AiReview[];aiRun?:AiRun|null;motivations?:Motivation[];motivationRun?:(ModelRun&{jobId?:string})|null;triageRun?:ModelRun|null;unscreened?:number;ownerFeedback?:Record<string,OwnerFeedback>;sameAs?:SameAs[];searchLimits?:{phrases:number;pages:number;pageSize:number;dailyRequests:number;hourlyRequests:number;storedResults:number};coverage?:{mode:string;terms:string[];pages:number;pageSize:number;attempted:number;succeeded:number;limited:boolean;dailyUsed:number;dailyLimit:number;at:string;queries:{term:string;page:number;count:number;status:string;error:string|null}[]};matching?:{version:string;cvReadAt:string|null;focus:string[];recommended:number;held:number};workflows?:ReviewWorkflow[];workflowNotice?:string|null;reviewRun?:null|{startedAt:string;finishedAt:string|null;status:string;prepared:number;held:number;unchanged:number;error:string|null};adzunaConfigured?:boolean;boards?:string;sources?:{id:string;source:string;status:string;at:string;count:number;error:string|null}[]};
type BaseScoutState={ownerStatuses?:Record<string,OwnerStatus>;interviewDates?:Record<string,{date:string;time:string;at:string}>;taskContext?:null|{workflowId:string|null;jobId:string};protected:boolean;configured:boolean;enabled:boolean;status:string;activeAgent:string|null;task:string|null;taskAt:string|null;lastRun:string|null;lastSuccess:string|null;nextCheck:string|null;error:string|null;stale:boolean;connectionError?:string;location:string;country?:string;distance:number;terms:string[];appId:string;profile:null|{name:string;skills:string[];terms:string[];wordCount:number;readAt:string;sourceUrl:string;focusLabels?:string[];evidence?:string[];qualificationMentions?:string[]};events:{id:string;date:string;agentId:string;type:string;details:string;source:string;handoff?:[string,string]}[];results:{id:string;sourceId:string;title:string;employer:string;location:string;url:string;description:string;skills:string[];salary:string;publishedAt:string|null;readAt:string;source:string;availability:string;stale?:boolean;fit?:MatchAssessment;completeness?:string;sourceExcerpt?:string;ownerTextAt?:string;foundOn?:string;modelFit?:{fit:string;reason:string;by:string;model:string;at:string}}[]};
// A posting the owner linked to a job already on the board: the same vacancy, found somewhere else.
export type SameAs={jobId:string;url:string;title:string;employer:string;source:string;recordId:string;at:string};
export type ScoutState=BaseScoutState & ReviewState & {version?:string};
const empty:ScoutState={protected:false,configured:false,enabled:false,status:'not-connected',activeAgent:null,task:null,taskAt:null,lastRun:null,lastSuccess:null,nextCheck:null,error:null,stale:false,location:'',country:'',distance:25,terms:[],appId:'',profile:null,events:[],results:[]};
const time=(s:string|null)=>s?new Date(s).toLocaleString('en-GB',{timeZone:zone()}):'Not recorded';
export function useScoutState(){
  const [state,setState]=useState<ScoutState>(empty),latest=useRef(state);latest.current=state;
  // The server sends the full state only when it changed; otherwise just the live task fields, and an identical state is not set again, so nothing redraws.
  const refresh=useCallback(async()=>{try{const held=latest.current.version,r=await fetch('/api/scout'+(held?'?since='+held:''),{cache:'no-store',signal:AbortSignal.timeout(30000)});if(!r.ok)throw new Error('Scout connection unavailable.');const next=await r.json() as Partial<ScoutState>&{unchanged?:boolean};if(next.unchanged){const {unchanged,...live}=next;setState(prev=>!prev.connectionError&&(Object.keys(live) as (keyof ScoutState)[]).every(key=>JSON.stringify(prev[key]??null)===JSON.stringify(live[key]??null))?prev:{...prev,...live,connectionError:undefined});}else setState({...empty,...next,connectionError:undefined});}catch{setState(prev=>({...prev,connectionError:'Execution connection unavailable; last received Scout data retained.',activeAgent:null,task:null,taskAt:null,taskContext:null}));}},[]);
  // Asked every three seconds while a task runs, once a minute otherwise, and not at all while the tab is in the background; coming back to the tab asks at once.
  useEffect(()=>{let stopped=false,timer:ReturnType<typeof setTimeout>;const poll=async()=>{clearTimeout(timer);if(document.hidden)return;await refresh();if(!stopped)timer=setTimeout(poll,latest.current.status==='running'?3000:60000);};const seen=()=>{if(!document.hidden)poll();};document.addEventListener('visibilitychange',seen);poll();return()=>{stopped=true;clearTimeout(timer);document.removeEventListener('visibilitychange',seen);};},[refresh]);
  return [state,refresh] as const;
}
// Settings shows the search controls; the raw suggestions and the task journal live on their own page.
export default function Scout({state,refresh,onConnections,view='settings'}:{state:ScoutState;refresh:()=>Promise<void>;onConnections:()=>void;view?:'settings'|'findings'}){
  const [appId,setAppId]=useState(state.appId),[appKey,setAppKey]=useState(''),[location,setLocation]=useState(state.location),[distance,setDistance]=useState(state.distance),[country,setCountry]=useState(state.country||''),[terms,setTerms]=useState(state.terms.join(', ')),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[details,setDetails]=useState<string|null>(null),[matchFilter,setMatchFilter]=useState('Recommended');
  useEffect(()=>{setAppId(state.appId);setLocation(state.location);setDistance(state.distance);setCountry(state.country||'');setTerms(state.terms.join(', '));},[state.appId,state.location,state.distance,state.terms.join(',')]);
  const action=async(action:string,config?:object)=>{setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/scout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...config}),signal:AbortSignal.timeout(60000)});const value=await r.json() as {error?:string;message?:string;verified?:boolean};if(!r.ok)throw new Error(value.error||'Scout action failed.');setNotice(value.message||(value.verified?'CV reading verified. Search terms and skills were extracted privately.':'Action completed.'));if(action==='save')setAppKey('');await refresh();}catch(e){setError(e instanceof Error?e.message:'Scout action failed.');await refresh();}finally{setBusy(false);}};
  const save=(e:FormEvent)=>{e.preventDefault();action('save',{appId,appKey,location,country,distance,terms});};
  const visibleResults=state.results.filter(j=>matchFilter==='All discoveries'||(matchFilter==='Recommended'?j.fit?.eligible&&ownerFeedbackFor(state,j.url,j.id)?.decision!=='not-fit':matchFilter==='Not a fit'?ownerFeedbackFor(state,j.url,j.id)?.decision==='not-fit':!j.fit?.eligible));
  const recommendedCount=state.results.filter(j=>j.fit?.eligible&&ownerFeedbackFor(state,j.url,j.id)?.decision!=='not-fit').length;
  const status=state.connectionError?'Connection unavailable':state.status==='running'?'Running a verified task':state.enabled?'Watching · waiting for next check':state.configured?'Paused / manual checks':'Connection needed';
  return <section className="scout-view">
    <div className="connections-intro"><span className="connection-emblem"><Search size={28}/></span><div><p className="eyebrow">{view==='findings'?'SCOUT FINDINGS / TASK JOURNAL':'DISCOVERY / AMSTERDAM AREA'}</p><h2>{view==='findings'?'What Scout found, and what HQ really ran.':'A Scout with real evidence.'}</h2><p>{view==='findings'?'Every source suggestion with its screening, then the journal of tasks this site actually carried out. The same vacancies appear in Jobs, where you act on them.':'Search Dutch vacancies using your CV. New suggestions stay outside your authoritative tracker until the Coordinator reviews them.'}</p></div></div>
    {view==='settings'&&<div className="scout-status"><Radio size={18}/><div><strong>{status}</strong><p>{state.task||'No current task is running.'}</p><small>Private HQ task runner · last successful check: {time(state.lastSuccess)}</small></div><span className="badge">{state.enabled?'Hourly checks':'Read only'}</span></div>}
    {(error||state.error||state.connectionError)&&<div className="connection-feedback error" role="alert"><Info size={18}/><p>{error||state.connectionError||state.error}{state.stale?' Last successful suggestions retained and stale.':''}</p></div>}
    {notice&&<div className="connection-feedback success" role="status"><Check size={18}/><p>{notice}</p></div>}
    {view==='settings'&&<>
    <div className="scout-grid"><article className="source-card"><header><FileText size={23}/><div><p className="eyebrow">PRIVATE CV READING</p><h3>{state.profile?.name||'Your CV'}</h3></div></header><p>Searches and screening read the CV you uploaded on My CV. Upload a new PDF there when your CV changes, then verify the reading here.</p><div className="scout-actions"><button className="subtle-button" onClick={onConnections}>Open My CV</button><button className="subtle-button" disabled={!state.protected||busy||state.status==='running'} onClick={()=>action('cv')}><RefreshCw size={15}/>Verify CV reading</button></div>{state.profile&&<><p className="quiet">Last read: {time(state.profile.readAt)} · {state.profile.wordCount} readable words</p><div className="skill-chips">{state.profile.skills.map(skill=><span key={skill}>{skill}</span>)}</div><p>CV-derived searches: {state.profile.terms.join(', ')||'None found; enter role searches below.'}</p></>}<small>CV contents stay on this server and are not sent to vacancy sources. Bounded professional evidence is retained privately for review drafts. Only professional role search terms and the location are sent. Scanned image PDFs need a text-based version.</small></article>
    <article className="source-card"><header><Search size={23}/><div><p className="eyebrow">VACANCY SOURCE</p><h3>Where you search · Adzuna</h3></div><span className="badge">{state.adzunaConfigured?'Key saved':'Key needed'}</span></header><form onSubmit={save}><label className="connection-field">Adzuna app ID · optional<input value={appId} onChange={e=>setAppId(e.target.value)} disabled={!state.protected||busy}/></label><label className="connection-field">Adzuna API key<input type="password" autoComplete="new-password" value={appKey} onChange={e=>setAppKey(e.target.value)} required={!!appId&&!state.adzunaConfigured} placeholder={state.adzunaConfigured?'Saved · leave blank to keep':'Only with an app ID'} disabled={!state.protected||busy}/></label><div className="scout-search-fields"><label className="connection-field">Search area<input value={location} onChange={e=>setLocation(e.target.value)} required maxLength={100} placeholder="Town or region" disabled={!state.protected||busy}/></label><label className="connection-field">Country code<input value={country} onChange={e=>setCountry(e.target.value.toLowerCase())} required maxLength={2} placeholder="us, gb, de, nl…" disabled={!state.protected||busy}/></label><label className="connection-field">Radius<select value={distance} onChange={e=>setDistance(Number(e.target.value))} disabled={!state.protected||busy}><option value={10}>10 km</option><option value={25}>25 km</option><option value={50}>50 km</option></select></label></div><label className="connection-field">Role searches · optional<input value={terms} onChange={e=>setTerms(e.target.value)} placeholder="Blank uses CV-derived roles · up to 6, comma-separated" disabled={!state.protected||busy}/></label><button className="subtle-button" disabled={!state.protected||busy||state.status==='running'}>Save private Scout settings <Check size={15}/></button></form><p className="quiet">Saving pauses future checks. Credentials are encrypted with your existing private settings.</p><a href="https://developer.adzuna.com/overview" className="text-button" target="_blank" rel="noreferrer">Get Adzuna API access <ExternalLink size={14}/></a></article></div>
    <div className="scout-run-controls"><div><strong>Scout checks while the hosting app runs.</strong><p>Find jobs checks up to six phrases, two pages and 50 listings per page. Hourly checks rotate through three Adzuna requests. Up to 72 Adzuna requests per UTC day; each employer board is read once per check. A ten-minute gap protects manual checks. Waiting is shown separately from working.</p><small>Next check: {time(state.nextCheck)} · Daily Coordinator schedule stays unchanged.</small></div><div className="scout-actions"><button className="subtle-button" disabled={!state.configured||busy||state.status==='running'} onClick={()=>action('run')}><RefreshCw size={15}/>Check now</button>{state.enabled?<button className="subtle-button" disabled={busy} onClick={()=>action('pause')}><Pause size={15}/>Pause watching</button>:<button className="primary-button" disabled={!state.configured||busy||state.status==='running'} onClick={()=>action('start')}><Play size={15}/>Start hourly Scout</button>}</div></div>
    {state.coverage&&<details className="daily-search-controls"><summary>Latest search coverage</summary><p>{state.coverage.attempted} Adzuna requests · {state.coverage.succeeded} successful · {state.coverage.dailyUsed} / {state.coverage.dailyLimit} daily requests used</p><p>{state.coverage.terms.join(', ')}</p>{state.coverage.queries.map((q,i)=><p key={i}>{q.term} · page {q.page} · {q.status==='synced'?q.count+' returned listings':q.error}</p>)}</details>}
    </>}
    {view==='findings'&&<>
    <div className="evidence-note"><ShieldCheck size={18}/><p>Scout records sources and the Analyst screens them: by keyword rules, and by your CV when you ask for model screening. Each suggestion shows which of the two recommended or held it. A suggestion is not a tracker record until you save it from Jobs.</p></div>
    <header className="scout-results-heading"><div><p className="eyebrow">SOURCE SUGGESTIONS / NOT TRACKER RECORDS</p><h2>{recommendedCount} CV-matched suggestions</h2><p className="quiet">{state.results.length} discoveries · {state.matching?.held??0} held outside the recommended list</p></div><a href="https://www.adzuna.nl" target="_blank" rel="noreferrer">Jobs by Adzuna <ExternalLink size={13}/></a></header>
    <div className="match-toolbar"><label>Show<select aria-label="Scout match filter" value={matchFilter} onChange={e=>setMatchFilter(e.target.value)}><option>Recommended</option><option>Held for mismatch</option><option>All discoveries</option><option>Not a fit</option></select></label><span className="quiet">CV focus: {state.matching?.focus.join(', ')||'Read your linked CV'} · evidence read {time(state.matching?.cvReadAt||null)}</span></div>
    <div className="scout-results">{visibleResults.map(result=><article key={result.id} className="source-card"><div className="event-title"><strong>{result.employer}</strong><span>{result.location}</span></div><h3>{result.title}</h3><p>{result.salary}</p><MatchEvidence fit={result.fit}/><div className="skill-chips">{result.skills.map(skill=><span key={skill}>{skill}</span>)}{!result.skills.length&&<span>No keyword overlap documented</span>}</div><p className="quiet">{result.availability}</p><small>{result.id} · source read: {time(result.readAt)}{result.stale?' · stale':''}</small><div className="scout-actions"><button className="text-button" onClick={()=>setDetails(details===result.id?null:result.id)}>{details===result.id?'Hide':'Show'} source excerpt</button><a className="text-button" href={result.url} target="_blank" rel="noreferrer">Open source vacancy <ExternalLink size={14}/></a></div>{details===result.id&&<p>{result.description||'Description not supplied.'} Full requirements, salary period, language and experience fit still require original vacancy review.</p>}</article>)}{!visibleResults.length&&<div className="empty-state"><Search size={25}/><p>{state.results.length?'No discoveries pass this filter. Held roles remain available with their reasons; run a new CV-focused source check for more candidates.':state.lastSuccess?'The last source check returned no matching suggestions.':'No completed vacancy check yet. Connect the source and verify CV reading to start.'}</p></div>}</div>
    <header className="scout-results-heading"><div><p className="eyebrow">VERIFIED HQ EVENTS</p><h2>Workflow execution journal</h2></div><span>Separate from the Sheet’s Activity Log</span></header><div className="activity-list">{[...state.events].reverse().slice(0,30).map(event=><article className="event-item" key={event.id}><span className="event-icon"><Radio size={16}/></span><div><div className="event-title"><strong>{agentName(event.agentId)} / {event.type}</strong><span>{time(event.date)}</span></div><p>{event.details}</p><small>{event.id} · {event.source}{event.handoff?' · recorded handoff '+event.handoff.map(agentName).join(' → '):''}</small></div></article>)}{!state.events.length&&<p className="quiet">No task execution has been recorded. Office movement is ambient.</p>}</div>
    </>}
  </section>;
}
