'use client';
import React,{useState,useEffect,useCallback,useRef} from 'react';
import {Layers3,Activity as ActivityIcon,ShieldCheck,Search,RefreshCw,Settings2,ChevronLeft,ChevronRight,Link2,WifiOff,ExternalLink,Sunrise,Radio,FileText} from 'lucide-react';
import {makeDemo,safeUrl,type Snapshot,type Activity,type Job} from './data';
import Connections from './connections';
import Scout,{useScoutState} from './scout';
import {AnalystAiSettings} from './analyst-ai';
import JSearchSettings from './job-sources';
import Workflow from './workflow';
import {useReviewLaunch} from './review-launch';
import DailyWorkspace,{type CvRequest} from './daily';
import ProfilePage from './profile';
import {compareActivityDates} from './activity-dates';
import type {JobGroup} from './daily-model';
import {zone} from './zone';
import ThemeSwitch from './theme';

type Tab='today'|'jobs'|'profile'|'settings'|'activity'|'connections'|'scout'|'workflow'|'findings';
const navigation=[{id:'today' as Tab,label:'Today',Icon:Sunrise},{id:'jobs' as Tab,label:'Jobs',Icon:Layers3},{id:'profile' as Tab,label:'My CV',Icon:FileText},{id:'settings' as Tab,label:'Settings',Icon:Settings2}];
const advancedTabs:Tab[]=['connections','scout','workflow','findings','activity'],every:Tab[]=['today','jobs','profile','settings',...advancedTabs];
function stamp(s:string|null){if(!s)return 'Never';if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const d=new Date(s);return Number.isNaN(d.getTime())?s:new Intl.DateTimeFormat('en-GB',{timeZone:zone(),day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(d);}
function EventItem({event,data,onJob}:{event:Activity;data:Snapshot;onJob:(j:Job)=>void}){const job=data.jobs.find(j=>j.id===event.recordId);return <article className="event-item"><span className={'event-icon '+event.category}>{event.category==='employer'?<Link2 size={17}/>:<ActivityIcon size={17}/>}</span><div><div className="event-title"><strong>{event.type}</strong><span>{stamp(event.date)}</span></div><p>{event.details}</p><div className="event-meta"><span className={'category '+event.category}>{event.category==='employer'?'Employer communication':event.category==='administrative'?'Administrative change':event.category==='candidate'?'Candidate communication':'Source activity'}</span><span>{event.id}</span>{job&&<button onClick={()=>onJob(job)}>{job.employer}</button>}</div><details><summary>View evidence</summary><p>{event.evidence||'Not recorded'}</p><p>{event.sourceDate&&event.sourceDate!==event.date?'Source date: '+event.sourceDate+' · ':''}Actor: {event.actor||'Unknown'} · Record: {event.recordId||'Unlinked'}</p>{safeUrl(event.evidence)&&<a href={safeUrl(event.evidence)!} target="_blank" rel="noreferrer">Open evidence <ExternalLink size={14}/></a>}</details></div></article>;}
// Replaced review versions pile up every time the CV or the screening changes. Removing them is permanent, so it is the owner's own two-step action.
function OldReviews({state,refresh}:{state:ReturnType<typeof useScoutState>[0];refresh:()=>Promise<void>}){
  const old=(state.workflows||[]).filter(w=>w.superseded&&!w.tracker).length,[sure,setSure]=useState(false),[busy,setBusy]=useState(false),[note,setNote]=useState(''),[error,setError]=useState('');
  async function remove(){if(busy)return;if(!sure){setSure(true);return;}setBusy(true);setError('');setNote('');try{const r=await fetch('/api/scout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'prune-reviews',confirm:true}),signal:AbortSignal.timeout(60000)}),v=await r.json() as {saved?:boolean;message?:string;error?:string};if(!r.ok||!v.saved)throw new Error(v.error||'Nothing was deleted.');setNote(v.message||'Deleted.');await refresh();}catch(e){setError(e instanceof Error?e.message:'Nothing was deleted.');}finally{setBusy(false);setSure(false);}}
  if(!state.protected||(!old&&!note))return null;
  return <details className="daily-search-controls"><summary>Storage · {old} old review versions</summary><p>Each time your CV or the screening changes, jobs are reviewed again and the earlier review is kept. These replaced versions are no longer used for anything on the site, and they are most of what the site has to load. Deleting them keeps the newest review of every job and every review that was saved to your tracker. It cannot be undone.</p>{error&&<p className="connection-feedback error" role="alert">{error}</p>}{note&&<p className="connection-feedback success" role="status">{note}</p>}{old>0&&<div className="job-decision-actions"><button className="subtle-button" disabled={busy||state.status==='running'} onClick={remove}>{busy?'Deleting…':sure?'Confirm: delete '+old+' old versions for good':'Delete '+old+' old review versions'}</button>{sure&&!busy&&<button className="text-button" onClick={()=>setSure(false)}>Cancel</button>}</div>}</details>;
}
// The whole app: a menu, the page for the chosen tab, and the two things every page needs, the tracker records and the state of the task runner.
export default function Shell(){
const [scout,refreshScout]=useScoutState();
const reviewLaunch=useReviewLaunch(scout,refreshScout);
const [data,setData]=useState<Snapshot>(makeDemo),[tab,setTab]=useState<Tab>(()=>{const hash=window.location.hash.slice(1) as Tab;return every.includes(hash)?hash:'today';}),[syncing,setSyncing]=useState(false),[navWide,setNavWide]=useState(()=>{try{return window.localStorage?.getItem('hq-nav-wide')==='1';}catch{return false;}}),[jobKey,setJobKey]=useState(''),[jobGroup,setJobGroup]=useState<JobGroup>('All jobs'),[category,setCategory]=useState('All events'),[cvRequest,setCvRequest]=useState<(CvRequest&{nonce:number})|null>(null);
const currentData=useRef(data);currentData.current=data;
useEffect(()=>{if(window.location.hash.slice(1)!==tab)window.history.pushState(null,'','#'+tab);},[tab]);
// Back, forward and a typed address lead to the page they name.
useEffect(()=>{const follow=()=>{const hash=window.location.hash.slice(1) as Tab;if(every.includes(hash))setTab(hash);};window.addEventListener('hashchange',follow);window.addEventListener('popstate',follow);return()=>{window.removeEventListener('hashchange',follow);window.removeEventListener('popstate',follow);};},[]);
useEffect(()=>{try{window.localStorage?.setItem('hq-nav-wide',navWide?'1':'0');}catch{/* optional */}},[navWide]);
// One failed read is tried again quietly before the page says the connection is interrupted.
const sync=useCallback(async()=>{setSyncing(true);try{let result:Snapshot|undefined,failure:unknown;for(let attempt=0;attempt<2&&!result;attempt++){if(attempt)await new Promise(done=>setTimeout(done,2500));try{const r=await fetch('/api/snapshot',{cache:'no-store',signal:AbortSignal.timeout(35000)}),v=await r.json() as Snapshot;if(!r.ok)throw new Error(v.error||'Connection unavailable.');result=v;}catch(e){failure=e;}}if(!result)throw failure;if(currentData.current.mode==='synced'&&result.mode==='demo')throw new Error('The database is no longer connected. Last successful records retained.');setData(result);return result;}catch(e){setData(prev=>({...prev,stale:true,error:e instanceof Error?e.message:'Connection unavailable.'}));}finally{setSyncing(false);}},[]);
// The tracker is read again every five minutes while the tab is in view, and when the owner comes back to it after more than a minute. Every save reads it again by itself.
useEffect(()=>{sync();let last=Date.now();const again=()=>{if(document.hidden)return;last=Date.now();sync();},interval=setInterval(again,300000),seen=()=>{if(!document.hidden&&Date.now()-last>60000)again();};document.addEventListener('visibilitychange',seen);return()=>{clearInterval(interval);document.removeEventListener('visibilitychange',seen);};},[sync]);
useEffect(()=>{if(!data.stale||data.mode==='demo')return;const timer=setInterval(()=>{if(!document.hidden)sync();},30000);return()=>clearInterval(timer);},[data.stale,data.mode,sync]);
const browseJobs=(group:JobGroup)=>{setJobGroup(group);setJobKey('');setTab('jobs');},selectJob=(key:string,group:JobGroup)=>{setJobKey(key);setJobGroup(group);if(key)setTab('jobs');},openJob=(job:Job)=>selectJob('tracker:'+job.id,'All jobs');
const sorted=[...data.events].sort(compareActivityDates).reverse(),visibleEvents=sorted.filter(e=>category==='All events'||(category==='Employer communication'&&e.category==='employer')||(category==='Administrative changes'&&e.category==='administrative')||(category==='Candidate communication'&&e.category==='candidate')).slice(0,300);
return <div className={'app simple-hq '+(navWide?'nav-wide ':'')}>
<header className="topbar"><a className="brand" href="#today" aria-label="Job Hunt home"><span className="brand-symbol">J<span>·</span></span><div><strong>Job Hunt</strong><small>YOUR SEARCH, ON YOUR MACHINE</small></div></a><div className="topbar-actions"><ThemeSwitch/><span className={'mode-pill '+(data.mode==='demo'?'demo':'synced')}><span/>{data.mode==='demo'?'DEMO MODE':'YOUR RECORDS'}</span></div></header>
<nav className="sidebar" aria-label="Main navigation"><div className="nav-items">{navigation.map(({id,label,Icon})=><button key={id} className={tab===id||id==='settings'&&advancedTabs.includes(tab)?'active':''} onClick={()=>setTab(id)} aria-current={tab===id||id==='settings'&&advancedTabs.includes(tab)?'page':undefined} aria-label={label} title={label}><Icon size={22}/><span>{label}</span></button>)}</div><div className="nav-bottom"><button className="nav-toggle" aria-label={navWide?'Narrow the menu':'Widen the menu'} aria-pressed={navWide} title={navWide?'Narrow the menu':'Widen the menu'} onClick={()=>setNavWide(v=>!v)}>{navWide?<ChevronLeft size={20}/>:<ChevronRight size={20}/>}</button><button aria-label="Setup and connections" title="Setup and connections" onClick={()=>setTab('connections')}><ShieldCheck size={22}/></button></div></nav>
<div className="workspace"><main className="main">
<div className="page-heading"><div><p className="eyebrow">JOB HUNT / {advancedTabs.includes(tab)?'SETTINGS':tab.toUpperCase()}</p><h1>{tab==='today'?'Your job hunt, today.':tab==='jobs'?'Your jobs':tab==='profile'?'My CV':tab==='settings'?'Settings':tab==='activity'?'Recorded activity':tab==='connections'?'Setup and connections':tab==='scout'?'Search settings':tab==='findings'?'Scout findings & journal':'Sources & imports'}</h1></div><div className="heading-actions"><button className={'subtle-button '+(syncing?'syncing':'')} onClick={sync} disabled={syncing}><RefreshCw size={15}/>{syncing?'Checking…':'Refresh'}</button></div></div>
<div className={'connection-strip '+(data.stale?'stale':'')}><div><span className="connection-dot"/><span>{data.stale?'Connection interrupted · stale data':data.mode==='demo'?'Demo · fictional records':'Your database · your records'}</span></div><span>{data.mode==='demo'?'Not connected yet':('Last read: '+stamp(data.syncedAt))}</span></div>
{data.stale&&<div className="error-notice" role="status"><WifiOff size={17}/><span>{data.error} Last successful data remains visible.</span></div>}
{advancedTabs.includes(tab)&&<button className="text-button settings-return" onClick={()=>setTab('settings')}><ChevronLeft size={16}/>Back to Settings</button>}
{(tab==='today'||tab==='jobs')&&<DailyWorkspace onPrepareCv={request=>{setCvRequest({...request,nonce:Date.now()});setTab('profile');}} mode={tab} data={data} state={scout} refresh={refreshScout} sync={sync} selected={jobKey} group={jobGroup} onSelect={selectJob} onGroup={browseJobs} onSettings={()=>setTab('settings')} onOffice={()=>setTab('today')} onRecheck={()=>reviewLaunch.run(false)} reviewBusy={reviewLaunch.busy} reviewNotice={reviewLaunch.notice} reviewError={reviewLaunch.error} replay={false}/>}
{tab==='settings'&&<section className="settings-hub"><p>Your connections and less frequent tools live here. Daily decisions stay together in Jobs.</p><div className="settings-cards">{[
 {id:'connections' as Tab,title:'Setup, database & mail',description:'The setup steps, where your records are kept, and the mailbox connection.',Icon:Link2},
 {id:'scout' as Tab,title:'Search preferences',description:'Vacancy sources, location, searches from your CV, the hourly check and the AI model.',Icon:Search},
 {id:'workflow' as Tab,title:'Sources & imports',description:'Employer boards and vacancies you paste in yourself.',Icon:Layers3},
 {id:'findings' as Tab,title:'Scout findings & journal',description:'Raw source suggestions with their screening, and the record of tasks that really ran.',Icon:Radio},
 {id:'activity' as Tab,title:'Activity',description:'The history entries of your tracked jobs.',Icon:ActivityIcon}
 ].map(({id,title,description,Icon})=><button key={id} onClick={()=>setTab(id)}><Icon size={24}/><div><strong>{title}</strong><p>{description}</p></div></button>)}</div><details className="daily-search-controls"><summary>Review export</summary><a className="subtle-button" href="/api/scout?report=pdf" aria-disabled={!scout.protected} onClick={e=>{if(!scout.protected)e.preventDefault();}}><Layers3 size={16}/>Download job review PDF</a></details><OldReviews state={scout} refresh={refreshScout}/></section>}
{tab==='activity'&&<section className="activity-view"><div className="view-intro"><p>{data.mode==='demo'?'Fictional demonstration entries.':'The history of your tracked jobs, newest first.'} These are records, not live messages.</p></div><div className="activity-filters">{['All events','Employer communication','Administrative changes','Candidate communication'].map(c=><button className={category===c?'active':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><div className="activity-list">{visibleEvents.map(e=><EventItem key={e.id} event={e} data={data} onJob={openJob}/>)}{!visibleEvents.length&&<div className="empty-state">No recorded entries match this category.</div>}</div></section>}
{tab==='connections'&&<Connections data={data} scout={scout} onProfile={()=>setTab('profile')} onSearch={()=>setTab('scout')}/>}
{tab==='profile'&&<ProfilePage onSettings={()=>setTab('connections')} scout={scout} request={cvRequest}/>}
{tab==='scout'&&<><Scout state={scout} refresh={refreshScout} onConnections={()=>setTab('profile')}/><JSearchSettings state={scout} refresh={refreshScout}/><AnalystAiSettings state={scout} refresh={refreshScout}/></>}
{tab==='findings'&&<Scout view="findings" state={scout} refresh={refreshScout} onConnections={()=>setTab('connections')}/>}
{tab==='workflow'&&<Workflow setupOnly state={scout} refresh={refreshScout} onAgent={()=>{}}/>}
<footer className="main-footer"><span><ShieldCheck size={13}/> Your records stay in your own database.</span><span>JOB HUNT</span></footer>
</main></div>
</div>;
}
