import {useEffect,useRef,useState} from 'react';
import {ExternalLink,Inbox,RefreshCw,X} from 'lucide-react';
import {recordsHome,type Snapshot} from './data';
import type {ScoutState} from './scout';
import {saveJobStatus} from './job-status-model';
import {zone} from './zone';
export type StatusSuggestion={recordId:string;status:string;reason:string};
export type ReplyProposal={key?:string;recordId:string;employer:string;role:string;current:string;status:string;label:string;subject:string;sender:string;receivedAt:string;excerpt:string;url:string;basis:string};
type Scan={checkedAt:string;scanned:number;capped:boolean;jobs:number;proposals:ReplyProposal[]};
const stamp=(at:string)=>new Date(at).toLocaleString('en-GB',{timeZone:zone(),day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});
// Applications that can still receive an answer.
export const awaitingReply=(data:Snapshot)=>data.jobs.filter(j=>['Applied','Submitted','Interview'].includes(j.status)&&/^JOB-\d{3,8}$/.test(j.id)).map(j=>({recordId:j.id,employer:j.employer,role:j.role,status:j.status,appliedOn:/^\d{4}-\d{2}-\d{2}$/.test(j.applied)?j.applied:''}));
// A proposal is only worth showing while the tracker still holds the status it was made against.
export const openProposals=(scan:Scan|null,data:Snapshot)=>(scan?.proposals||[]).filter(p=>data.jobs.some(j=>j.id===p.recordId&&j.status===p.current));
export const suggestionFor=(p:ReplyProposal):StatusSuggestion=>({recordId:p.recordId,status:p.status,reason:('Outlook message "'+p.subject+'" from '+p.sender+', received '+stamp(p.receivedAt)+'.').slice(0,480)});
// The Tracker reads recent Outlook replies and proposes a status for the owner to confirm. It never changes a status itself.
export default function TrackerInbox({data,state,replay,onReview,onOpen,onSettings,refresh,sync}:{data:Snapshot;state:ScoutState;replay:boolean;refresh:()=>Promise<void>;sync:()=>Promise<Snapshot|undefined>;onReview:(suggestion:StatusSuggestion)=>void;onOpen:(recordId:string)=>void;onSettings:()=>void}){
  const [mail,setMail]=useState<{connected?:boolean;scan?:Scan|null;error?:string|null}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),inFlight=useRef(false),[sure,setSure]=useState('');
  const real=data.mode==='synced'&&state.protected,jobs=awaitingReply(data);
  useEffect(()=>{if(!real)return;let stopped=false;fetch('/api/mail',{cache:'no-store',signal:AbortSignal.timeout(15000)}).then(r=>r.ok?r.json():null).then(v=>{if(!stopped&&v)setMail(v);}).catch(()=>{});return()=>{stopped=true;};},[real]);
  async function check(){if(inFlight.current||!real||replay)return;inFlight.current=true;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/mail',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'scan',jobs}),signal:AbortSignal.timeout(90000)}),v=await r.json() as {result?:Scan;message?:string;error?:string};if(!r.ok||!v.result)throw new Error(v.error||'Outlook check unavailable.');setMail(m=>({...m,connected:true,scan:v.result}));setNotice(v.message||'Checked.');}catch(e){setError(e instanceof Error?e.message:'Outlook check unavailable.');}finally{inFlight.current=false;setBusy(false);}}
  async function remove(key:string){if(inFlight.current||replay)return;inFlight.current=true;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/mail',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'remove-reply',key}),signal:AbortSignal.timeout(30000)}),v=await r.json() as {saved?:boolean;scan?:Scan|null;message?:string;error?:string};if(!r.ok||!v.saved)throw new Error(v.error||'Not removed.');setMail(m=>({...m,scan:v.scan||null}));setNotice(v.message||'Removed.');}catch(e){setError(e instanceof Error?e.message:'Not removed.');}finally{inFlight.current=false;setBusy(false);}}
  // Sets the proposed status straight from the list, after a second, confirming click. It is the same owner-confirmed write as the status editor, with the email named as the reason.
  async function apply(p:ReplyProposal){if(inFlight.current||replay||!p.status||!p.key)return;if(sure!==p.key){setSure(p.key);return;}const job=data.jobs.find(j=>j.id===p.recordId);if(!job)return;inFlight.current=true;setBusy(true);setError('');setNotice('');try{const receipt=await saveJobStatus({action:'status',recordId:job.id,requestId:'HQ-S-'+crypto.randomUUID(),status:p.status,expectedStatus:job.status,expectedApplied:job.applied,reason:suggestionFor(p).reason,confirmStatus:true});const r=await fetch('/api/mail',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'remove-reply',key:p.key}),signal:AbortSignal.timeout(30000)}).then(r=>r.ok?r.json():null).catch(()=>null) as {scan?:Scan|null}|null;if(r)setMail(m=>({...m,scan:r.scan||null}));setNotice(p.employer+': '+receipt.status+' confirmed in '+recordsHome(data)+' · '+receipt.recordId+' / '+receipt.eventId);await refresh();await sync();}catch(e){setError((e instanceof Error?e.message:'The status was not saved.')+' Open the job to see or retry the request.');}finally{inFlight.current=false;setBusy(false);setSure('');}}
  if(!real)return null;
  const proposals=openProposals(mail?.scan||null,data);
  return <section className="tracker-inbox" aria-label="Replies in Outlook">
    <header><Inbox size={20}/><div><strong>Replies in Outlook</strong><small>{mail?.connected?jobs.length+' application'+(jobs.length===1?'':'s')+' waiting for a reply'+(mail.scan?' · last checked '+stamp(mail.scan.checkedAt):' · not checked yet'):'Outlook is not connected'}</small></div>{mail?.connected?<button className="subtle-button" disabled={busy||replay||!jobs.length} onClick={check}><RefreshCw size={15}/>{busy?'Reading…':'Check for replies'}</button>:<button className="subtle-button" onClick={onSettings}>Connect Outlook</button>}</header>
    {error&&<p className="connection-feedback error" role="alert">{error}</p>}{notice&&!error&&<p className="connection-feedback success" role="status">{notice}</p>}
    {proposals.map(p=><article key={p.key||p.recordId} className={'tracker-proposal '+(p.status||'note').toLowerCase().replace(/\s/g,'-')}><div><span>{p.label}</span><strong>{p.employer} · {p.role}</strong><p>“{p.subject}” · {p.sender} · {stamp(p.receivedAt)}</p><small>{p.excerpt}</small><small className="quiet">{p.basis} {p.status?'This is a guess from the words in the message. Read the email before you set it; the tracker still says '+p.current+'.':'No status is proposed for this one. Read the email and change the status yourself if it calls for it.'}</small></div><div className="tracker-proposal-actions">{p.status?<><button className="primary-button" disabled={busy||replay||!p.key||state.status==='running'} onClick={()=>apply(p)}>{sure===p.key?(busy?'Saving…':'Confirm: set '+p.status+' in '+recordsHome(data)):'Set '+p.status}</button>{sure===p.key&&!busy?<button className="text-button" onClick={()=>setSure('')}>Cancel</button>:<button className="text-button" disabled={busy} onClick={()=>onReview(suggestionFor(p))}>Edit before saving</button>}</>:<button className="subtle-button" onClick={()=>onOpen(p.recordId)}>Open the job</button>}{p.url&&<a className="text-button" href={p.url} target="_blank" rel="noreferrer">Open the email <ExternalLink size={14}/></a>}{p.key&&<button className="text-button" disabled={busy||replay} title="Not about this job, or already dealt with" onClick={()=>remove(p.key!)}><X size={14}/>Remove from list</button>}</div></article>)}
    {mail?.connected&&mail.scan&&!proposals.length&&!notice&&<p className="quiet">No open proposal. The last check read {mail.scan.scanned} recent messages{mail.scan.capped?' (the newest '+mail.scan.scanned+')':''}.</p>}
  </section>;
}
