import {useEffect,useState,type FormEvent} from 'react';
import {ArrowRight,Check,ExternalLink,FileText,Layers3,Link2,Search} from 'lucide-react';
import type {ScoutState} from './scout';
import {MatchEvidence,canAppendReview,type MatchAssessment,type MatchReview} from './match';
import './workflow.css';
import {zone} from './zone';
export type ReviewWorkflow=MatchReview & {fit?:MatchAssessment;id:string;createdAt:string;cvReadAt:string;stage:string;managerDecision:string;job:{id:string;sourceId:string;source:string;title:string;employer:string;location:string;salary:string;url:string;description:string;readAt:string;availability:string;stale?:boolean};receipts:{id:string;agentId:string;at:string;inputReceipt:string|null;title:string;method:string;findings:{label:string;value:string}[];decision:string}[];draft:null|{letter:string;cvBullets:string[];interviewQuestions:string[];kind:string};tracker:null|{recordId:string;eventId:string;at:string;duplicate:boolean}};
// The preparation and outstanding-checks steps are the Analyst's work; the save to the database is the Tracker's.
const names:Record<string,string>={'01':'Scout','02':'Analyst','03':'Analyst · preparation','04':'Analyst · open checks','00':'Tracker'};
const stamp=(s:string)=>new Date(s).toLocaleString('en-GB',{timeZone:zone()});
export default function Workflow({state,refresh,onAgent,initialAgent='02',initialWorkflowId='',setupOnly=false}:{state:ScoutState;refresh:()=>Promise<void>;onAgent:(id:string)=>void;initialAgent?:string;initialWorkflowId?:string;setupOnly?:boolean}){
  const [selected,setSelected]=useState(''),[agent,setAgent]=useState('02'),[query,setQuery]=useState(''),[filter,setFilter]=useState('All stages'),[boards,setBoards]=useState(state.boards||''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reviewed,setReviewed]=useState(false),[matchFilter,setMatchFilter]=useState('Recommended'),[history,setHistory]=useState(false);
  useEffect(()=>{setAgent(initialAgent);setSelected(initialWorkflowId);if(initialWorkflowId){const w=state.workflows?.find(w=>w.id===initialWorkflowId);if(!w?.currentFit?.eligible)setMatchFilter('All discoveries');if(w?.superseded)setHistory(true);}},[initialAgent,initialWorkflowId]);
  useEffect(()=>setBoards(state.boards||''),[state.boards]);
  const workflows=state.workflows||[],filtered=[...workflows].reverse().filter(w=>(history||!w.superseded)&&(matchFilter==='All discoveries'||(matchFilter==='Recommended'?w.currentFit?.eligible:!w.currentFit?.eligible))&&(filter==='All stages'||w.stage===filter)&&(w.job.title+' '+w.job.employer+' '+w.id).toLowerCase().includes(query.toLowerCase())),chosen=workflows.find(w=>w.id===selected&&filtered.includes(w))||filtered[0],receipt=chosen?.receipts.find(r=>r.agentId===agent)||chosen?.receipts.at(-1);
  useEffect(()=>setReviewed(false),[chosen?.id]);
  async function action(action:string,body:object){setBusy(true);setError('');setNotice('');try{const response=await fetch('/api/scout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...body}),signal:AbortSignal.timeout(60000)}),result=await response.json() as {error?:string;message?:string};if(!response.ok)throw new Error(result.error||'Action failed.');setNotice(result.message||'Saved.');await refresh();}catch(e){setError(e instanceof Error?e.message:'Connection unavailable.');}finally{setBusy(false);}}
  function importJob(e:FormEvent<HTMLFormElement>){e.preventDefault();action('import',Object.fromEntries(new FormData(e.currentTarget)));}
  const locked=!state.protected||!!state.connectionError||busy||state.status==='running';
  return <section className="workflow-view">
    <div className="connections-intro"><span className="connection-emblem"><Layers3 size={28}/></span><div><p className="eyebrow">DISCOVER / EVALUATE / PREPARE / REVIEW</p><h2>{setupOnly?'Search sources & private imports':'Follow the evidence.'}</h2><p>{setupOnly?'Manage employer feeds, import a vacancy you found and maintain your private Coordinator connection. Review the resulting job in Jobs.':'Each job keeps its source, input receipt, findings and handoff. Private drafts become tracker records after a verified Coordinator append.'}</p></div></div>
    {(error||state.connectionError)&&<div className="connection-feedback error" role="alert">{error||state.connectionError}</div>}{notice&&<div className="connection-feedback success" role="status"><Check size={17}/>{notice}</div>}{state.workflowNotice&&<div className="error-notice">{state.workflowNotice}</div>}
    {!setupOnly&&<><div className="source-health">{state.sources?.map(s=><article key={s.id}><strong>{s.source}</strong><span className={s.status==='error'?'source-error':''}>{s.status==='synced'?s.count+' source matches':'Unavailable · retained evidence may be stale'}</span><small>Checked {stamp(s.at)}</small>{s.error&&<p>{s.error}</p>}</article>)}</div>
    <div className="evidence-note"><FileText size={19}/><p>Local evidence checks, factual draft templates and completeness review. No full AI fit score is claimed. No CV is sent to job boards. No application is submitted.</p></div>
    <div className="scout-run-controls"><div><strong>Continue with recorded Scout discoveries.</strong><p>Analyst checks the linked CV, Application prepares drafts only after CV role and qualification screening passes, and Manager records the outstanding checks. Earlier review versions are preserved; stale sources need a new Scout check.</p>{state.reviewRun&&<small>{state.reviewRun.status==='running'?'Review in progress':state.reviewRun.status==='failed'?'Last review failed: '+state.reviewRun.error:`Last review: ${state.reviewRun.prepared} new versions · ${state.reviewRun.held} Analyst holds · ${state.reviewRun.unchanged} unchanged`}{state.reviewRun.finishedAt?' · '+stamp(state.reviewRun.finishedAt):''}</small>}</div><button className="primary-button" disabled={locked||!state.results.some(j=>!j.stale)} onClick={()=>action('review',{})}><Layers3 size={16}/>Let's start reviewing</button></div>
    <div className="workflow-toolbar"><label className="search-field"><Search size={17}/><input aria-label="Find a review" placeholder="Find employer, role or workflow…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Review stage" value={filter} onChange={e=>setFilter(e.target.value)}><option>All stages</option><option>Coordinator review</option><option>Analyst hold</option></select><a className="subtle-button" href="/api/scout?report=pdf" aria-disabled={!state.protected} onClick={e=>{if(!state.protected)e.preventDefault();}}><FileText size={16}/>Download review PDF</a></div>
    <div className="match-toolbar"><label>CV screening<select aria-label="Review match filter" value={matchFilter} onChange={e=>setMatchFilter(e.target.value)}><option>Recommended</option><option>Held for mismatch</option><option>All discoveries</option></select></label><label><input type="checkbox" checked={history} onChange={e=>setHistory(e.target.checked)}/>Include previous review versions</label><span className="quiet">Current CV screening appears separately from preserved receipts.</span></div>
    <div className="workflow-workbench"><div className="workflow-list" aria-label="Review workflows">{filtered.map(w=><button className={chosen?.id===w.id?'selected':''} onClick={()=>{setSelected(w.id);setAgent('02');}} key={w.id}><span>{w.job.employer}</span><strong>{w.job.title}</strong><small>{w.currentFit?.label||'Screening unavailable'} · {w.currentRules?'Current review':'Re-review needed'} · {w.tracker?w.tracker.recordId:w.stage} · {stamp(w.createdAt)}</small></button>)}{!filtered.length&&<div className="empty-state">No reviews pass this filter. Inspect held discoveries for the reason, or start reviewing to prepare current reviews.</div>}</div>
    {chosen?<article className="workflow-detail"><header><p className="eyebrow">{chosen.tracker?'VERIFIED TRACKER RECEIPT':'PRIVATE REVIEW / NOT A TRACKER RECORD'}</p><h2>{chosen.job.title}</h2><p>{chosen.job.employer} · {chosen.job.location}</p><a className="text-button" href={chosen.job.url} target="_blank" rel="noreferrer">Open {chosen.job.source} source <ExternalLink size={14}/></a><small>{chosen.job.sourceId} · source read {stamp(chosen.job.readAt)} · CV read {stamp(chosen.cvReadAt)}</small><p className="quiet">{chosen.job.availability} This is a saved review version; inspect the current vacancy before acting.</p></header>
      <MatchEvidence fit={chosen.currentFit} previous={!chosen.currentRules}/>{chosen.superseded&&<p className="quiet">Previous review version. Select the latest version before acting.</p>}
      <div className="receipt-steps" aria-label="Agent review trail">{chosen.receipts.map((r,i)=><div key={r.id}><button className={receipt?.id===r.id?'active':''} onClick={()=>setAgent(r.agentId)}>{names[r.agentId]}</button>{i<chosen.receipts.length-1&&<ArrowRight size={14}/>}</div>)}</div>
      {receipt&&<section className="receipt-content"><div className="event-title"><strong>{receipt.title}</strong><button className="text-button" onClick={()=>onAgent(receipt.agentId)}>Visit workspace</button></div><p className="receipt-decision">{receipt.decision}</p><p className="quiet">{receipt.method} · {stamp(receipt.at)}</p><dl>{receipt.findings.map((f,i)=><div key={i}><dt>{f.label}</dt><dd>{f.value}</dd></div>)}</dl><small>Receipt: {receipt.id}<br/>Input: {receipt.inputReceipt||chosen.job.source+' / '+chosen.job.sourceId}</small></section>}
      <details className="review-fold"><summary>Vacancy evidence as received</summary><p>{chosen.job.description}</p></details>
      {chosen.draft&&canAppendReview(chosen)&&<details className="review-fold"><summary>Application draft & interview preparation</summary><p className="quiet">{chosen.draft.kind}. Owner review required.</p><h3>Letter draft</h3><pre>{chosen.draft.letter}</pre><h3>CV evidence to consider</h3><ul>{chosen.draft.cvBullets.map((s,i)=><li key={i}>{s}</li>)}</ul><h3>Interview questions</h3><ul>{chosen.draft.interviewQuestions.map((s,i)=><li key={i}>{s}</li>)}</ul></details>}
      <div className="coordinator-action"><p className="eyebrow">00 / COORDINATOR</p><h3>{chosen.tracker?'Tracker append verified':chosen.managerDecision}</h3>{chosen.tracker?<p>{chosen.tracker.recordId} · {chosen.tracker.eventId} · {stamp(chosen.tracker.at)}{chosen.tracker.duplicate?' · matched an existing record':''}</p>:<><p>Proposed discovery: <b>Researching / Pending review</b>. Role receipts go into HQ Workflow Log in the same Sheet. Application approval is separate.</p><label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)} disabled={locked||!chosen.draft||!canAppendReview(chosen)}/> I reviewed the source and want this discovery added.</label><button className="primary-button" disabled={locked||!reviewed||!chosen.draft||!canAppendReview(chosen)} onClick={()=>action('append',{workflowId:chosen.id,confirmReviewed:true})}><Check size={16}/>Add reviewed discovery</button></>}</div>
    </article>:<div className="workflow-detail empty-state"><Layers3 size={32}/><h3>Your review trail starts with a real source.</h3><p>Scout checks create dated receipts. Waiting agents have no active task.</p></div>}</div>
    </>}
    <div className="scout-grid"><article className="source-card"><header><Search size={23}/><div><p className="eyebrow">PUBLIC EMPLOYER FEEDS</p><h3>Direct source coverage</h3></div></header><p>Greenhouse, Ashby, Lever and Lever EU read configured employer boards. Declared locations are matched locally; the Adzuna kilometre radius does not apply.</p><form onSubmit={e=>{e.preventDefault();action('sources',{boards});}}><label className="connection-field">Employer boards · up to eight<textarea rows={7} value={boards} onChange={e=>setBoards(e.target.value)} disabled={locked}/><small>Optional. Add a line only for a company whose careers page you want watched closely: HTTPS board URL | employer name. Leave empty to rely on the broad search alone.</small></label><button className="subtle-button" disabled={locked}>Save employer boards</button></form><p className="quiet">Lever example: https://jobs.lever.co/employer | Employer. Each configured board reports its own connection status.</p></article>
    <article className="source-card"><header><Link2 size={23}/><div><p className="eyebrow">LINKEDIN / INDEED / OTHER SOURCES</p><h3>Import a vacancy</h3></div></header><p>Copy the vacancy description you can access. HQ records your excerpt without fetching or scraping the link. These platforms are not automatically connected.</p><div className="scout-actions"><a className="text-button" target="_blank" rel="noreferrer" href={'https://www.linkedin.com/jobs/search/?keywords='+encodeURIComponent(state.terms[0]||state.profile?.terms[0]||'CRO')+'&location='+encodeURIComponent(state.location)}>Search LinkedIn <ExternalLink size={14}/></a><a className="text-button" target="_blank" rel="noreferrer" href={'https://nl.indeed.com/jobs?q='+encodeURIComponent(state.terms[0]||state.profile?.terms[0]||'CRO')+'&l='+encodeURIComponent(state.location)}>Search Indeed <ExternalLink size={14}/></a></div><form onSubmit={importJob}><label className="connection-field">Vacancy URL<input name="url" type="url" required placeholder="https://…" disabled={locked}/></label><label className="connection-field">Employer<input name="employer" required maxLength={120} disabled={locked}/></label><label className="connection-field">Location<input name="location" maxLength={120} disabled={locked}/></label><label className="connection-field">Role title<input name="title" required maxLength={180} disabled={locked}/></label><label className="connection-field">Salary · optional<input name="salary" maxLength={150} placeholder="Unknown if omitted" disabled={locked}/></label><label className="connection-field">Copied requirements & description<textarea name="description" rows={6} required minLength={80} maxLength={18000} disabled={locked}/></label><button className="subtle-button" disabled={locked}>Import & prepare review</button></form></article></div>
  </section>;
}
