// A dependency-free, paginated PDF. Text is transliterated to the built-in Latin font.
const ascii=s=>String(s??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[–—→]/g,'-').replace(/·/g,' | ').replace(/[‘’]/g,"'").replace(/[“”]/g,'"').replace(/…/g,'...').replace(/[^\x20-\x7e\n]/g,'?');
const escape=s=>s.replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');
function wrap(text){return ascii(text).split('\n').flatMap(line=>{const words=line.split(/\s+/),out=[];let current='';for(const word of words){if(current.length+word.length>94){out.push(current);current='';}if(word.length>94){for(let i=0;i<word.length;i+=94)out.push(word.slice(i,i+94));}else current+=(current?' ':'')+word;}out.push(current);return out;});}
export function reviewPdf(workflows,at=new Date().toISOString()){
  const lines=['JOB HUNT HQ - COORDINATOR REVIEW LIST','Generated: '+at,'Private draft review evidence. Not a submission or application approval.','Tracker records exist only where a verified JOB / EVT receipt is shown.',''];
  if(!workflows.length)lines.push('No reviewed source suggestions have been recorded.');
  for(const w of workflows){if(w.currentFit)lines.push(...wrap((w.currentFit.eligible?'CV SCREENING: ':'HELD - EXCLUDED FROM RECOMMENDATIONS: ')+w.currentFit.label),...wrap(w.currentFit.blockers.join(' ')));if(w.currentRules===false)lines.push('Earlier saved review: re-review under current rules before acting.');lines.push(...wrap(w.job.employer+' / '+w.job.title),...wrap('Workflow: '+w.id),...wrap('Source: '+w.job.source+' / '+w.job.sourceId+' | read: '+w.job.readAt),...wrap('URL: '+w.job.url),...wrap('Location: '+w.job.location+' | Salary: '+w.job.salary),...wrap('Review: '+w.managerDecision+' | Stage: '+w.stage),...wrap('Tracker: '+(w.tracker?w.tracker.recordId+' / '+w.tracker.eventId:'Not added')));for(const r of w.receipts){lines.push(...wrap(r.agentId+' / '+r.decision+' / '+r.at));for(const f of r.findings)lines.push(...wrap(f.label+': '+f.value));}lines.push('','--------------------------------------------------------------------------','');}
  const pages=[];for(let i=0;i<lines.length;i+=49)pages.push(lines.slice(i,i+49));
  const objects=['','<< /Type /Catalog /Pages 2 0 R >>','','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];
  const pageIds=[];pages.forEach((lines,index)=>{const pageId=objects.length,streamId=pageId+1;pageIds.push(pageId);const commands=['BT','/F1 9 Tf','12 TL','42 795 Td',...lines.flatMap(line=>['('+escape(line)+') Tj','T*']),'ET','BT /F1 8 Tf 42 28 Td ('+escape('Job Hunt | Private review | Page '+(index+1)+' of '+pages.length)+') Tj ET'].join('\n');objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R >> >> /Contents ${streamId} 0 R >>`,`<< /Length ${Buffer.byteLength(commands)} >>\nstream\n${commands}\nendstream`);});
  objects[2]=`<< /Type /Pages /Count ${pageIds.length} /Kids [${pageIds.map(id=>id+' 0 R').join(' ')}] >>`;
  let document='%PDF-1.4\n',offsets=[0];for(let i=1;i<objects.length;i++){offsets.push(Buffer.byteLength(document));document+=i+' 0 obj\n'+objects[i]+'\nendobj\n';}const start=Buffer.byteLength(document);document+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF\n`;return Buffer.from(document);
}
